### ISSUE TITLE
Properties, Layout, and Code Tab Aren't Changing with New Node Selections

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#102]
Originally reported by: **Carl Walker (Bitbucket: [walkerca](https://bitbucket.org/walkerca), GitHub: [walkerca](https://github.com/walkerca))**

----------------------------------------

On Ubuntu 16.04, after loading an FXML from the new welcome screen, I wasn't able to change the contents of the right-most panels (Properties, Layout, Code) after the first selection.

1. Start SceneBuilder
2. From the Welcome screen, select an FXML file
3. Select a Node from the Hierarchy or canvas; verify that the Node's data is on the right
4. Select another Node

The panels retain their properties from Step 3

Build Information
Version 8.3.0
Date: 2016-12-16
Java Version: 1.8.0_111-b14, Oracle Corporation

I couldn't find a .log file

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/102

**Comment by AlmasB** [comment]
Cannot reproduce in SB19 on Windows 10. Please reopen if the issue remains.
