### ISSUE TITLE
Dark Theme not loaded at startup

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#103]
Originally reported by: **Marcelo Ruiz (Bitbucket: [MarceloJRuiz](https://bitbucket.org/MarceloJRuiz), GitHub: Unknown)**

----------------------------------------

SceneBuilder does not honor preference to use the Dark Theme at startup.
It shows it's supposed to be using the dark theme under preferences (so the option is saved and kept between restarts) but it starts with the Default Theme enabled. Changing the preference to the Default Theme and back to the Dark Theme shows the Dark Theme.

JavaFX Scene Builder 8.3.0

Build Information
Version 8.3.0
Date: 2016-12-16
Java Version: 1.8.0_111-b14, Oracle Corporation

Logging
The default configuration stores logging output in a file named scenebuilder-8.3.0.log (possibly followed by a trailing '.' and a digit).
The default file path is /tmp/scenebuilder-8.3.0.log

JavaFX
Toolkit = QuantumToolkit
Pipeline = ES2Pipeline
Hardware acceleration ENABLED

Java
1.8.0_111-b14, Oracle Corporation

Operating System
Linux, amd64, 4.4.0-53-generic

Copyright (c) 2015-2016, Gluon.

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/103

**Comment by AlmasB** [comment]
Cannot reproduce in SB 19 on Windows 10. The dark theme is enabled from start if it was previously set before exit. Please reopen if the issue remains.
