### ISSUE TITLE
Can't Operate on Multiple FXML Files

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#105]
Originally reported by: **Carl Walker (Bitbucket: [walkerca](https://bitbucket.org/walkerca), GitHub: [walkerca](https://github.com/walkerca))**

----------------------------------------

If I create more than one FXML file using New, the latter instances of Scene Builder don't allow me to add controls.

1. Open Scene Builder
2. Create a new FXML and drag a container on the canvas
3. Save the new FXML file (important)
4. Create a new FXML
5. Attempting to drag a container on the new canvas does not allow the drop

Build Information
Version 8.3.0
Date: 2016-12-16
Java Version: 1.8.0_111-b14, Oracle Corporation

Operating System
Linux, amd64, 4.4.0-59-generic

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/105

**Comment by AlmasB** [comment]
Cannot reproduce using SB 19 on Windows 10. Please reopen if the issue still remains.

**Comment by Oliver-Loeffler** [comment]
Its also not occurring on macOS Monterey (x86) with FX19, Java 19.
