### ISSUE TITLE
Uncaught Exception when right-clicking (popup-menu) on Hierarchy

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#108]
Originally reported by: **Anonymous**

----------------------------------------

Hi,

I got this exception (attachment) when using Scene Builder 8.3.0. No popup menu appears, which is the bug. I suspect it has something to do with a custom component I've included... when I remove this custom component, the popup menu appears again, without Scene Builder restart.

This is my setup (from "About Scene Builder" menu)

--------------------

Product Version
JavaFX Scene Builder 8.3.0

Build Information
Version 8.3.0
Date: 2016-12-16
Java Version: 1.8.0_111-b14, Oracle Corporation

Logging
The default configuration stores logging output in a file named scenebuilder-8.3.0.log (possibly followed by a trailing '.' and a digit).
The default file path is /tmp/scenebuilder-8.3.0.log

JavaFX
Toolkit = QuantumToolkit
Pipeline = ES2Pipeline
Hardware acceleration ENABLED

Java
1.8.0_111-b14, Oracle Corporation

Operating System
Linux, amd64, 4.8.0-37-generic

Copyright (c) 2015-2016, Gluon.

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/108

**Comment by abhinayagarwal** [comment]
Incomplete issue
