### ISSUE TITLE
Accelerators of Scene Builder don't work always

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#110]
Originally reported by: **Anonymous**

----------------------------------------

Hey,

the accelerators of Scene Builder (e.g. Ctrl-S) don't work anymore when the .fxml has exactly  the same accelerators configured.

I have a Ctrl-S accelerator in my Save-MenuItem, and from the point in time I added this, the Ctrl-S of Scene Builder doesn't do anything anymore.

(My environment is in the attachments)

Kind regards,
Stefan

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/110

**Comment by abhinayagarwal** [comment]
The attachments and user information has been lost during the migration. Closing the issue as incomplete.
