### ISSUE TITLE
Spinner not supported 100%

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#119]
Originally reported by: **RoiEX (Bitbucket: [RoiEX](https://bitbucket.org/RoiEX), GitHub: [RoiEX](https://github.com/RoiEX))**

----------------------------------------

Currently Spinners can't be configured to use a Factory...
The only way to predefine values is by adding them manually to the fxml file.
You should be able to do that from inside the Scene Builder

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/119

**Comment by AlmasB** [comment]
Bumped via #614
