### ISSUE TITLE
SceneBuilder freezes all my system

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#125]
Originally reported by: **Anonymous**

----------------------------------------

After some minutes of light working, scene builder makes my cursor progresively slower, keyboard doesnt work and I have to restart my laptop.
It is not an old laptop (Inspiron 5559) and Im using a fresh install of kde neon.

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/125

**Comment by abhinayagarwal** [comment]
This is a very old issue and these issues have not been reported with recent releases of SB.
