### ISSUE TITLE
Broken dialogs when using a tiling window manager

### ISSUE THREAD

**Issue by cilki** [gluonhq/scenebuilder#182]
Some dialogs in Scene Builder 9.0.1 open as tiny white boxes under a tiling window manager (I'm using dwm). I tested Scene Builder 8.4.1 and all dialogs open as expected.

![2018-05-31-100328_847x335_scrot](https://user-images.githubusercontent.com/10459406/40790906-c7c9972c-64bb-11e8-9d87-1d902d6f1bb9.png)

This issue occurs for File->Preferences, Help->Check For Update, and some other dialogs (Help->About works though). The open/save dialogs also seem to work since they are GTK.

I'm on Arch Linux 4.16.11-1 x86_64 and Scene Builder installed from [here](https://aur.archlinux.org/packages/javafx9-scenebuilder/).

**Comment by cilki** [comment]
@moacirrf I just got around to testing this.

I can confirm your commit fixes the preferences window and check for update, but I discovered two more dialogs where the error occurs:

- Closing SceneBuilder without saving
- Attempting to save a new file without `.fxml`

Thanks for your help!

**Comment by moacirrf** [comment]
Thanks! I will correct this too, i wonder if it is a SceneBuilder or a Jfx runtime problem, but call Stage.sizeToScene() in a separate thread works well.

Platform.runLater(() -> getStage().sizeToScene());
Quite frankly i dont know if it is a good practice.

**Comment by moacirrf** [comment]
I think i Fixed this issue too, sorry for late.
https://github.com/gluonhq/scenebuilder/commit/219e61e176be8b14ddc181bc80c1298573f8f3ab
https://github.com/gluonhq/scenebuilder/commit/9f1a4589db76b468c723ed838d55e4bf1be9eea2

**Comment by moacirrf** [comment]
This bug apparently was fixed on scene builder 11? or in runtime 11.
Someone can confirm?
Because i cant reproduce it anymore.

**Comment by cilki** [comment]
@moacirrf I'll test out the latest commit when I get a chance.

**Comment by moacirrf** [comment]
I tried run Scene builder 10 with Runtime 11, and the dialogs broke.
But Scene Builder 11 with runtime 11 no problems.
I published Scene Builder 11 on Aur
https://aur.archlinux.org/packages/javafx11-scenebuilder/

**Comment by cilki** [comment]
This is what I get on 4.19.8-arch1-1-ARCH.

[hs_err_pid4318.log](https://github.com/gluonhq/scenebuilder/files/2683077/hs_err_pid4318.log)

**Comment by moacirrf** [comment]
Hi,
I did some changes on native Gtk libs, can someone test if it correct this bug, please?
1- Download my compiled libs and extract in somewhere.
[CompiledLib.zip](https://github.com/gluonhq/scenebuilder/files/2818155/CompiledLib.zip)
2- Go to /opt/SceneBuilder-11/runtime/lib/, or in your SceneBuilder directory.
3- Make a security copy of the files: libglass.so, libglassgtk2.so, libglassgtk3.so.
4- Copy the downloaded files to /opt/SceneBuilder-11/runtime/lib
5- Execute SceneBuilder

Obs.: 
Open SceneBuilder.cfg, change gtk version to 3 or 2, so we can ensure that is working on both versions.
...
[JVMOptions]
**-Djdk.gtk.version=2**
...

Thanks

**Comment by moacirrf** [comment]
Im very happy that you are using, my AUR version of Scene Builder.
Thanks

**Comment by moacirrf** [comment]
If you are curious about the changes you can checkout here:
https://github.com/moacirrf/openjdk-jfx/commit/cdc93af49cc85ae7bf86e1601243734bfcb73ffd

**Comment by abhinayagarwal** [comment]
Can you guys reproduce this bug when running from source using `./gradlew run`?

The reason I ask this is because the `run` task [force usage of GTK-2](https://github.com/gluonhq/scenebuilder/blob/master/app/build.gradle#L17). In case this is a GTK-3 issue, we can add a JVM argument to the linux script to use GTK-2 by default.

**Comment by moacirrf** [comment]
Yes, this is a problem of Gtk with kde.

**Comment by moacirrf** [comment]
Its the same issue reported here.
https://github.com/javafxports/openjdk-jfx/issues/222

**Comment by abhinayagarwal** [comment]
If this is a platform specific bug, I would rather close this issue linking to the OpenJFX issue. Let me know if you guys are ok with it?

**Comment by cilki** [comment]
@abhinayagarwal No problem, I didn't realize there was an OpenJFX issue for this one.
