### ISSUE TITLE
Japanese characters in the main menu are garbled in executable jar built on Windows OS Japanese editin.

### ISSUE THREAD

**Issue by torutk** [gluonhq/scenebuilder#195]
Regarding #194. To approach this issue,  I built from source code on Windows PC in Japanese environment.
My built executable jar shows the garbled menu text, it is different from #194 garble.

The build is the following steps:

1. git clone from scene builder repository, use branch "integration-9".
2. build with gradle (gradlew clean build)
3. run executable jar

The result shows garbled menu texts.

![image](https://user-images.githubusercontent.com/2397032/44623784-6c39cc00-a913-11e8-93e1-a1d732c19256.png)

I look up the properties file for japanese in source code repository, in official released 10.0.0 executable jar(not garbled), and in my build(garbled).
To comparison easely, only look up one key and value pare of 'menu.title.file' which is shown in menu bar [File(F)] 

- In source code repository, the line is as follows. (written in UTF-8 text)

![image](https://user-images.githubusercontent.com/2397032/44623841-0e0de880-a915-11e8-9d57-e35c8e21bb9e.png)

- In official released executable jar, the line is as follows. (written in escaped unicode text)

> menu.title.file = \u30d5\u30a1\u30a4\u30eb(F)

- In my build executable jar, the line is as follows. (written in escaped unicode text)

> menu.title.file = \u7e5d\u8f14\u3043\u7e67\uff64\u7e5d\uff6b(F)

This garble is typically occuured in Java 

by reading UTF-8 text file using java.io.FileReader API with default encoding in Windows Japanese environment.
Windows Japanese environment uses Not UTF-8 but Windows_31J encoding.

I guess this miss encoding is caused by running gradle on not UTF-8 encoding environment.

**Comment by torutk** [comment]
I built from source code on Linux PC in Japanese environment.
Fedora 28, Oracle JDK 10.0.2. LANG=ja_JP.UTF-8
My built executable jar is OK, shows no garbled menu text.

**Comment by torutk** [comment]
In app/build.gradle, properties files is processed by the line as follows:

> filter(EscapeUnicode)

This is only valid when the properties file encoding is the same as system encoding.
So, Linux Japanese environment is OK, but Windows Japanese environment is not OK.

To avoid garble build on Windows Japanese environment, modify gradlew.bat
from
> set DEFAULT_JVM_OPTS=
to
> set DEFAULT_JVM_OPTS="-Dfile.encoding=UTF-8"

But as side effect of changing file.encoding to UTF-8, gradle output message is garbled on Windows command prompt. (Windows command prompt is not UTF-8 encoding)

**Comment by tawAsh1** [comment]
If you use the "master" branch, will garbled text be displayed?
I think this problem is very similar to # 186.
I would like to address it.

**Comment by torutk** [comment]
I failed to build "master" branch with Oracle JDK 10.0.2 on Windows.
It seemed that "master" branch does not support JDK 10 (may be JDK 9+).

- fix wrapper\gradle-wrapper.properties to use gradle-4.10.1 instead of 2.4.

run gradlew clean build, then some errors occurred.

`
> Task :kit:compileJava
scenebuilder_master\kit\src\main\java\com\oracle\javafx\scenebuilder\kit\editor\report\CSSParsingReport.java:35: error: package com.sun.javafx.css does not exist
import com.sun.javafx.css.CssError;
  :(snip)
  (package com.sun.javafx.css is declared in module javafx.graphics, which does not export it to the unnamed module)
`

**Comment by abhinayagarwal** [comment]
You are hit by a Gradle bug - https://github.com/gradle/gradle/issues/2270

And yes master is for JDK 8 and integration-9 branch is for JDK 9+.

**Comment by torutk** [comment]
Thank you for giving me a comment.
This issue is primary caused by Gradle. I will check the Gradle more.

**Comment by abhinayagarwal** [comment]
Hi @torutk ,

Can you check if you can reproduce the issue on both master(with JDK 8) and intergration-9 (with JDK9+) ?

If it can be reproduced, can you check if the issue is resolve by running:

```
./gradlew run -Dfile.encoding=UTF-8
```

**Comment by torutk** [comment]
I tried to reproduce this issue on master branch.

The summary result is as follows:
 
- The issue is reproduced with JDK 8
- The issue is resolved by run task with command line option `-Dfile.encoding=UTF-8`.
Although clean is needed.

As for integration-9 branch, it came to the same result.

The detail of work on master branch is as follows:

OS: Windows 10 64bit Japanese Edition
JDK: Oracle JDK 8u172 64bit
build command line: 
```
gradlew clean build
```
run command line:
```
java -jar app\build\libs\scenebuilder-8.5.0-SNAPSHOT-all.jar
```
Screen appears with garble as follows:
![image](https://user-images.githubusercontent.com/2397032/46092502-f82f6400-c1ef-11e8-8fbf-3cf052fc1793.png)

Then, run command line:
```
gradlew run -Dfile.encoding=UTF-8
```
Screen appears with garble same as above.
The garble issue is in build process, so clean and run command line as follows:
```
gradlew clean run -Dfile.encoding=UTF-8
```
Screen appears without garble as follows:
![image](https://user-images.githubusercontent.com/2397032/46093937-a25cbb00-c1f3-11e8-9a07-973a8cd22eca.png)

**Comment by abhinayagarwal** [comment]
I am guessing adding `-Dfile.encoding=UTF-8` to `gradle clean build` will fix the first case as well?

```
gradlew clean build -Dfile.encoding=UTF-8
```

**Comment by torutk** [comment]
Yes, this issue is fixed with adding command line option '-Dfile.endoding=UTF-8' to gradlew.
I close this issue.
Thank you for your kind guidance.

**Comment by abhinayagarwal** [comment]
Can you also close PR #196? 

I will create a new PR to fix the build scripts. Thank you for all the testing.
