### ISSUE TITLE
Where do I find the code / branch for release 8.5.0

### ISSUE THREAD

**Issue by mkarneim** [gluonhq/scenebuilder#197]
Hi there!

I have some weird bug concerning a custom component that can't be found by the library manager.
I'd like to investigate this by debugging Scenebuilder, but **I can't find the source code for the specific version I am using**, which is 8.5.0 from June 2018.

Could anybody give me some hint where I can find it?

Cheers 
Michael

**Comment by tiainen** [comment]
The tag for version 8.5.0 was missing. I've added the tag to the corresponding commit.

See https://github.com/gluonhq/scenebuilder/tree/8.5.0

**Comment by mkarneim** [comment]
Great.
Thanks!
