### ISSUE TITLE
SceneBuilder 10.0.0 fails to detect Ikonli's FontIcon

### ISSUE THREAD

**Issue by aalmiray** [gluonhq/scenebuilder#200]
https://github.com/aalmiray/ikonli provides a class named `FontIcon` that extends from `javafx.scene.text.Text`.

https://github.com/aalmiray/ikonli/blob/master/subprojects/ikonli-javafx/src/main/java/org/kordamp/ikonli/javafx/FontIcon.java

Importing the required JARs using the Libray Manager (see screenshot1) does not show potential components/elements to be imported (see screenshot2)

<img width="1269" alt="scenebuilder-1" src="https://user-images.githubusercontent.com/13969/48266560-fdf3a880-e42f-11e8-8526-f395e51fb8c2.png">
<img width="1258" alt="scenebuilder-2" src="https://user-images.githubusercontent.com/13969/48266561-fe8c3f00-e42f-11e8-8004-a154733a637a.png">

**Comment by aalmiray** [comment]
Relates to https://github.com/aalmiray/ikonli/issues/39

**Comment by jperedadnr** [comment]
Scene Builder 11, with support for Java/JavaFX 11, imports fine `ikonli-javafx:11+`.
