### ISSUE TITLE
Is there a schedule for the Java-11-compatible release?

### ISSUE THREAD

**Issue by jjyyxx** [gluonhq/scenebuilder#202]
From the commit records, it seems that Java 11 support has been enabled on the `master` branch. I would like to know how long it will take or is there an exact date or schedule for this version being released?

Sorry in advance if it's an imappropriate issue.

**Comment by jjyyxx** [comment]
Sorry I missed it somehow. I will try it out. 
Btw, since jfx is not shipped with java 11, does scene builder bundle the jfx module internally or require some other configurations? Thank you very much!

**Comment by jperedadnr** [comment]
The installer contains an image with JavaFX, so you can use the executable as usual.

**Comment by jjyyxx** [comment]
Got it.

**Comment by Vampire** [comment]
> There is already a RC published here: https://gluonhq.com/products/scene-builder/#download
> Can you try it? GA will be released soon.

May I ask when "soon" will be?
