### ISSUE TITLE
Opening fxml file doesn't apply default css to containers

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/scenebuilder#207]
When an existing FXML is opened (and there are no other SB windows running), the default modena css of the containers is not applied. After resizing it, for instance, it is applied.

For instance open SB and choose a template (like `Basic Application`):

<img width="1352" alt="sb" src="https://user-images.githubusercontent.com/2043230/49689010-f13f9e80-fb1a-11e8-8117-41fabcd0685e.png">

Only after resizing or modifying some property, the main container styling is applied.

**Comment by jperedadnr** [comment]
This issue happens since the [changes required for Java 9](https://github.com/gluonhq/scenebuilder/commit/9f6caa0fa63222cfc784ce890edffd4f25b7c503), and it can be inspected with ScenicView: the top container added to the subScene misses the `root` style class. After changing some property on the inspector panel, the style class is added.

**Comment by abhinayagarwal** [comment]
I am unable to reproduce this behaviour by selecting "Basic Application" from Desktop template.

Product Version:
JavaFX Scene Builder 11.0.0-SNAPSHOT (running from master-branch)

Build Information:
Ubuntu 18.04.1
Java Version: 11+28, Oracle Corporation

**Comment by jperedadnr** [comment]
I can reproduce it on Windows and Mac. 

It is only happening once, after you select to open an existing FXML file or new template (basic application) from the popup dialog. After that, it works fine. 

There is a refresh call that adds the `root` style class to the root container (this happens always after the first time), but I'm not sure if the initial dialog prevents this from happening to the first selected FXML.

**Comment by mikehearn** [comment]
I can also reproduce this. Is there anything we can do to help? All I've done is installed Scene Builder 10 and then created a new empty project.

**Comment by jperedadnr** [comment]
There is already a PR with a possible fix: #208 
You can try it if you build SB yourself with the proposed patch.

**Comment by jperedadnr** [comment]
It can be easily reproduced if you have some custom libraries that are imported while Scene Builder opens.
