### ISSUE TITLE
Update Notification on new Scene Builder Version

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#21]
Originally reported by: **Alexander Casall (Bitbucket: [acasall](https://bitbucket.org/acasall), GitHub: Unknown)**

----------------------------------------

SB should tell me whether there is a new version to download.

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/21

**Comment by Oliver-Loeffler** [comment]
@abhinayagarwal This item can be closed, afaik Scene Builder checks for updates and provides a notification to the user.
