### ISSUE TITLE
Scenebuilder not opening my .fxml file

### ISSUE THREAD

**Issue by Xeno247** [gluonhq/scenebuilder#211]
So I've downloaded a repo from GitHub.
https://github.com/afsalashyana/Library-Assistant

to be exact, and I want to make some modifications to the application developed here, add some classes and UI elements.

There's around 10 different .fxml files on this project and only 2 of them open up properly. There's no error message with the other .fxml files, they just dont open up at all. Like there's literally no response from them. The 2 that open up have a similar structure and layout. I'll post the code for one of the working ones here - basically it's a list of items from my database.

`<?xml` version="1.0" encoding="UTF-8"?>

<?import com.jfoenix.controls.JFXButton?>
<?import com.jfoenix.controls.JFXPasswordField?>
<?import com.jfoenix.controls.JFXTextField?>
<?import de.jensd.fx.glyphs.fontawesome.FontAwesomeIconView?>
<?import javafx.scene.layout.AnchorPane?>
<?import javafx.scene.text.Font?>

<AnchorPane id="AnchorPane" prefHeight="367.0" prefWidth="419.0" stylesheets="@../../../../resources/dark-theme.css" xmlns="http://javafx.com/javafx/8.0.141" xmlns:fx="http://javafx.com/fxml/1" fx:controller="library.assistant.ui.login.LoginController">
   <children>
      <JFXTextField fx:id="username" labelFloat="true" layoutX="95.0" layoutY="122.0" prefHeight="33.0" prefWidth="259.0" promptText="Username">
         <font>
            <Font size="16.0" />
         </font>
      </JFXTextField>
      <JFXPasswordField fx:id="password" labelFloat="true" layoutX="97.0" layoutY="194.0" onAction="#handleLoginButtonAction" prefHeight="34.0" prefWidth="259.0" promptText="Password">
         <font>
            <Font size="17.0" />
         </font>
      </JFXPasswordField>
      <JFXButton layoutX="106.0" layoutY="278.0" onAction="#handleLoginButtonAction" prefHeight="40.0" prefWidth="90.0" styleClass="login-button" text="Login" />
      <JFXButton layoutX="239.0" layoutY="278.0" onAction="#handleCancelButtonAction" prefHeight="40.0" prefWidth="90.0" styleClass="login-button" text="Cancel" />
      <FontAwesomeIconView glyphName="LOCK" layoutX="200.0" layoutY="79.0" size="55" />
      <FontAwesomeIconView glyphName="USER" layoutX="64.0" layoutY="149.0" size="25" />
      <FontAwesomeIconView glyphName="KEY" layoutX="64.0" layoutY="224.0" size="25" />
   </children>
</AnchorPane>`

And the one that doesnt work has data to be entered in it basically, and looks like this;

`<?xml version="1.0" encoding="UTF-8"?>

<?import com.jfoenix.controls.JFXButton?>
<?import com.jfoenix.controls.JFXPasswordField?>
<?import com.jfoenix.controls.JFXTextField?>
<?import de.jensd.fx.glyphs.fontawesome.FontAwesomeIconView?>
<?import javafx.scene.layout.AnchorPane?>
<?import javafx.scene.text.Font?>

<AnchorPane id="AnchorPane" prefHeight="367.0" prefWidth="419.0" stylesheets="@../../../../resources/dark-theme.css" xmlns="http://javafx.com/javafx/8.0.141" xmlns:fx="http://javafx.com/fxml/1" fx:controller="library.assistant.ui.login.LoginController">
   <children>
      <JFXTextField fx:id="username" labelFloat="true" layoutX="95.0" layoutY="122.0" prefHeight="33.0" prefWidth="259.0" promptText="Username">
         <font>
            <Font size="16.0" />
         </font>
      </JFXTextField>
      <JFXPasswordField fx:id="password" labelFloat="true" layoutX="97.0" layoutY="194.0" onAction="#handleLoginButtonAction" prefHeight="34.0" prefWidth="259.0" promptText="Password">
         <font>
            <Font size="17.0" />
         </font>
      </JFXPasswordField>
      <JFXButton layoutX="106.0" layoutY="278.0" onAction="#handleLoginButtonAction" prefHeight="40.0" prefWidth="90.0" styleClass="login-button" text="Login" />
      <JFXButton layoutX="239.0" layoutY="278.0" onAction="#handleCancelButtonAction" prefHeight="40.0" prefWidth="90.0" styleClass="login-button" text="Cancel" />
      <FontAwesomeIconView glyphName="LOCK" layoutX="200.0" layoutY="79.0" size="55" />
      <FontAwesomeIconView glyphName="USER" layoutX="64.0" layoutY="149.0" size="25" />
      <FontAwesomeIconView glyphName="KEY" layoutX="64.0" layoutY="224.0" size="25" />
   </children>
</AnchorPane>`

There's nothing I can do to fix it. I've added all custom libraries and jar files and I am literally lost.

**Comment by malikoski** [comment]
Have you installed the JFoenix components?

**Comment by abhinayagarwal** [comment]
@Xeno247 Please add one of the failing FXMLs to the issue for us to diagnose.

**Comment by jperedadnr** [comment]
It looks like, as @malikoski commented, it is a matter of missing libraries.

Closing this issue as that has an easy fix.
