### ISSUE TITLE
Scene Builder is setting "id" not "fx:id" in XML

### ISSUE THREAD

**Issue by mikehearn** [gluonhq/scenebuilder#215]
FXML generated by the latest Scene Builder seems wrong in a subtle way - the id attribute needs to be "fx:id" for it to be recognised by FXMLLoader in Java 8 but it's being generated as just "id", which doesn't work.

**Comment by abhinayagarwal** [comment]
I cannot reproduce this from the code in master branch. @mikehearn Can you please add more details to the issue along with the FXML being created by SB?

**Comment by mikehearn** [comment]
I'll try on master at some point.

**Comment by jperedadnr** [comment]
I'm closing this issue as there are not enough info to reproduce it.
