### ISSUE TITLE
In Scene Builder 10 some dropdowns and property edit widgets are semi-transparent

### ISSUE THREAD

**Issue by mikehearn** [gluonhq/scenebuilder#216]
I've installed JFoenix into Scene Builder, maybe that's related? My own CSS has nothing that could trigger this.

![semi-transparent-widget](https://user-images.githubusercontent.com/971089/50735181-d52b2d80-11aa-11e9-86c6-93f36b62a5eb.png)

**Comment by abhinayagarwal** [comment]
I have never been able to reproduce this. If we get any further information on this in future, this issue can be re-opened.
