### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by teyter** [gluonhq/scenebuilder#218]
I am using Solus Budgie. I desperately need Scene Builder for school. I apologize if it is inappropriate to post this here and of the formatting below is horrendous. It is the output from my terminal when I attempted to ./gradlew clean build. Any help would be greatly appreciated.

`Starting a Gradle Daemon (subsequent builds will be faster)

> Task :kit:compileJava FAILED
/home/teytur/uni/vidmot_HBV201/scenebuilder/kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/search/SearchController.java:38: error: cannot access StringProperty
import javafx.beans.property.StringProperty;
                            ^
  bad class file: /home/teytur/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-base/11/f8d1ced6047b010f1e3bb92dc060862179ce5897/javafx-base-11-linux.jar(javafx/beans/property/StringProperty.class)
    class file has wrong version 54.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kit:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 56s
4 actionable tasks: 1 executed, 3 up-to-date
`

**Comment by eugener** [comment]
Your error gives you a pretty clear explanation -
You seem to be building under Java 8 (class version 52), while it should be at least Java 10 (class version 54)

**Comment by teyter** [comment]
But I am using Java 8. The readme says to use the 8ue-dev branch which I did. Am I not meant to be able to build using Java 8?

**Comment by eugener** [comment]
You are clearly using JavaFX 11:

/home/teytur/.gradle/caches/modules-2/files-2.1/**org.openjfx/javafx-base/11**/f8d1ced6047b010f1e3bb92dc060862179ce5897/javafx-base-11-linux.jar(javafx/beans/property/StringProperty.class)

**Comment by teyter** [comment]
Sorry I posted the output of my initial attempt where I cloned the master branch. Here is the output where I do './gradlew clean build' having cloned from 8ue-dev branch:

`Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Task :kit:compileJava
warning: /home/teytur/.gradle/caches/modules-2/files-2.1/com.gluonhq/charm-glisten/5.0.0-jdk9/9ff9cf3bf5ca115c13138d5c7c13999eb60e3299/charm-glisten-5.0.0-jdk9.jar(com/gluonhq/charm/glisten/visual/GlistenStyleClasses.class): major version 53 is newer than 52, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: /home/teytur/.gradle/caches/modules-2/files-2.1/com.gluonhq/charm-glisten/5.0.0-jdk9/9ff9cf3bf5ca115c13138d5c7c13999eb60e3299/charm-glisten-5.0.0-jdk9.jar(com/gluonhq/charm/glisten/control/BottomNavigation.class): major version 53 is newer than 52, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: /home/teytur/.gradle/caches/modules-2/files-2.1/com.gluonhq/charm-glisten/5.0.0-jdk9/9ff9cf3bf5ca115c13138d5c7c13999eb60e3299/charm-glisten-5.0.0-jdk9.jar(com/gluonhq/charm/glisten/control/DropdownButton.class): major version 53 is newer than 52, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: /home/teytur/.gradle/caches/modules-2/files-2.1/com.gluonhq/charm-glisten/5.0.0-jdk9/9ff9cf3bf5ca115c13138d5c7c13999eb60e3299/charm-glisten-5.0.0-jdk9.jar(com/gluonhq/charm/glisten/control/ExpansionPanel.class): major version 53 is newer than 52, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
warning: /home/teytur/.gradle/caches/modules-2/files-2.1/com.gluonhq/charm-glisten/5.0.0-jdk9/9ff9cf3bf5ca115c13138d5c7c13999eb60e3299/charm-glisten-5.0.0-jdk9.jar(com/gluonhq/charm/glisten/control/ToggleButtonGroup.class): major version 53 is newer than 52, the highest major version supported by this compiler.
  It is recommended that the compiler be upgraded.
/home/teytur/uni/vidmot_HBV201/scenebuilder/kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/report/CSSParsingReport.java:36: error: cannot access CssParser
import javafx.css.CssParser;
                 ^
  bad class file: /home/teytur/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-graphics/11/4ab9edd8d481a420044c473fdb5718ccdd35c836/javafx-graphics-11-linux.jar(javafx/css/CssParser.class)
    class file has wrong version 54.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

> Task :kit:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kit:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 0s
4 actionable tasks: 1 executed, 3 up-to-date
`

**Comment by tiainen** [comment]
It looks like you are still building from the master branch. Check which branch you are currently on with `git branch`. Use `git checkout -f 8u-dev` to switch to the correct branch.

**Comment by teyter** [comment]
BUILD SUCCESFUL. That worked! My mistake was that I just changed over to the branch on github and cloned from there. I didn't realize I had to checkout branch. Scenebuilder is installed and launches successfully. Thank you so much!
