### ISSUE TITLE
Pasted values are duplicated in section Properties -> Style

### ISSUE THREAD

**Issue by TimurJD** [gluonhq/scenebuilder#221]
I'm using:
```
Product Version
JavaFX Scene Builder 10.0.0

Build Information
Version 10.0.0
Date: 2018-06-05
Java Version: 10.0.1+10, Oracle Corporation
....
....
Operating System
Mac OS X, x86_64, 10.13.6

```

whenever I copy a value and paste it to the **Properties -> Style** I see the value is duplicated in one field: `#2b4496#2b4496`

For example, I want to use color `#2b4496` for style `-fx-background-color` -> I copy the value `#2b4496` somewhere and paste it as value in the scene builder and get the value `#2b4496#2b4496`. It always happens when I use hot keys for copy/paste in my Mac OS Command+C/Command+V, but it works just fine when I use mouse right click -> copy -> paste.

**Comment by jperedadnr** [comment]
Actually this seems to be a JavaFX bug. 

It can be reproduced on Mac, when there is a _system_ `MenuBar` with a `MenuItem` that has an the accelerator set to `Cmd+V`, and a `TextField`.

Given that the TextField also has an internal key event handler based on the same key combination, both events are processed. 

To reproduce:

```
    @Override
    public void start(Stage stage) {
       TextField textField = new TextField();

        MenuItem paste = new MenuItem("Paste");
        paste.setOnAction(e -> textField.paste());
        paste.setAccelerator(new KeyCodeCombination(KeyCode.V, KeyCombination.META_DOWN));
        Menu menu = new Menu("Edit");
        menu.getItems().add(paste);
        MenuBar menuBar = new MenuBar(menu);
        menuBar.setUseSystemMenuBar(true);

        BorderPane pane = new BorderPane(textField);
        pane.setTop(menuBar);

        Scene scene = new Scene(pane, 300, 200);
        stage.setScene(scene);
        stage.show();
    }
```

now copy something to the clipboard and paste it using Cmd+V, it will be duplicated.

**Comment by abhinayagarwal** [comment]
This is a JavaFX bug and has been reported in OpenJFX repository - https://github.com/javafxports/openjdk-jfx/issues/370
