### ISSUE TITLE
Scene builder 11 black background issue

### ISSUE THREAD

**Issue by jschlade** [gluonhq/scenebuilder#225]
Using:

Product Version: JavaFX Scene Builder 11.0.0
Build Information: Version 11.0.0
Date: 2018-11-23
Java Version: 11.0.1+13-LTS, Oracle Corporation
Operating System: Windows 10, amd64, 10.0

I was playing around with the themes in scene builder to see what others looked like and now I can't get my forms to consistantly load with with a normal white backgroud. Sometimes they show up black like this:

![black](https://user-images.githubusercontent.com/13022731/52532803-56b93280-2cf8-11e9-9346-ebc6579c525e.PNG)

Instead of normally like this:

![white](https://user-images.githubusercontent.com/13022731/52532805-56b93280-2cf8-11e9-91d3-bbbc57b6eef7.PNG)

The only way around it is to flip flop re-opening a new window with them, As you can see both forms are identical and don't have a background setting for this. What the heck is going on with scene builder? Where does scenebuilder store it settings? Is there some setting that got messed up?

[Test2.fxml.txt](https://github.com/gluonhq/scenebuilder/files/2848770/Test2.fxml.txt)
[Test3.fxml.txt](https://github.com/gluonhq/scenebuilder/files/2848771/Test3.fxml.txt)

Thanks

**Comment by jperedadnr** [comment]
Duplicated of #207 
PR pending: #208
