### ISSUE TITLE
Why does the SceneBuilder installer need administrator privileges?

### ISSUE THREAD

**Issue by karneimm** [gluonhq/scenebuilder#243]
When I open the installer for scene builder (java 11) on windows (7) it says I need administrator privileges. This is annoying if you work on a computer where you don't have those rights.

Why is this?
Can this be worked around?

**Comment by Oliver-Loeffler** [comment]
I don't know how to workaround that yet but have an idea for Win10. Until then, I need to understand how the MSI file is created.

**Comment by Oliver-Loeffler** [comment]
Well, on a work project I was able to create an MSI installer which works without administrator priviledges. Therefore I'll create a PR with the required changes soon.
