### ISSUE TITLE
Wrong xmlns created by Scenebuilder?

### ISSUE THREAD

**Issue by HelmutL** [gluonhq/scenebuilder#248]
The FXML file created by Scenbuilder 11 (javafx 12, openjdk 12) contains xmlns="http://javafx.com/javafx11.0.1"
This leads to errors in Netbeans when manually editing the FXML file.
17.06.2019, 08:40:55 : Retrieving Location: http://javafx.com/javafx11.0.1 
Error: An I/O error occured. no protocol: /technetwork/java/javafx/index.html

**Comment by jperedadnr** [comment]
What is your NetBeans version? Where does that error happens? In the FXML file edited with NetBeans? You still can run the JavaFX project, can't you?

**Comment by HelmutL** [comment]
It is Apache Netbeans 11. The deerror happens when I edit the FXML file in Netbensa (e.g. to adapt coordinates or similar). The error appears in Netbeans, also two popup to accept an Oracle certificate.
![netbeans-fxml-certificate-Window](https://user-images.githubusercontent.com/17042607/59589783-fe9d9d00-90ea-11e9-8aa3-82cac7f64841.png)

**Comment by HelmutL** [comment]
reopen because closed by mistake

**Comment by HelmutL** [comment]
The project runs without problems.

**Comment by jperedadnr** [comment]
Did you accept the certificates? That should fix it

**Comment by HelmutL** [comment]
I did accept the certificates. But next time I am asked again.

**Comment by jperedadnr** [comment]
I see, but the issue is not related to Scene Builder, or `xmlns`, just by editing the FXML, NetBeans will try to download some files to parse the XML syntax, and for that the certificates might be required if somehow these expired. This will require an issue here: https://issues.apache.org/jira/secure/CreateIssue!default.jspa

**Comment by AlmasB** [comment]
It appears the issue is not related to SB, hence closed.
