### ISSUE TITLE
Scene Builder crash

### ISSUE THREAD

**Issue by otoman** [gluonhq/scenebuilder#249]
Right click on any item in Hierarchy pane should bring context menu. When you have MenuButton with no MenuItem (you want add them programatically) like in atteched fxml Scene Builder does nothing and randomly crash... I think it is bug. Tested in SceneBuilder 11.0.0
[Problem.zip](https://github.com/gluonhq/scenebuilder/files/3305305/Problem.zip)

**Comment by abdeelmadjid** [comment]
same problem also crash when press Ctrl+c

**Comment by kpamela** [comment]
I've been having the same issue, including when navigating towards the "Edit" menu. It seems that any action related to the Edit menu, Undo, redo, copy, paste, makes it crash

**Comment by Oliver-Loeffler** [comment]
At least on Windows, with Scene Builder 16, no crashes occurr. But, the context menu does not open.

@abhinayagarwal 
What is the policy on creating bug fixes for old versions of Scene Builder? The issue can be probably solved for version 11.

**Comment by abhinayagarwal** [comment]
There will be no releases for SB 11.x. SB 16 cab be used to produce FXMLs which are JavaFX 11 compatible. If there is a bug in 11.x and not reproducible in master, it is already fixed ;)
