### ISSUE TITLE
[FEATURE] add option in settings to show sample controller skeleton in Kotlin

### ISSUE THREAD

**Issue by Blackdread** [gluonhq/scenebuilder#259]
Just simple feature to add a switch in options to decide which language to use for "Show sample controller skeleton".
Not very important as copying java into kotlin with Intellij IDEA automatically translate the code to kotlin (not exactly as needed but quite close)

Something like:
```
class XXXController {

    @FXML
    private lateinit var emailTextField: TextField

    @FXML
    private lateinit var passwordTextField: PasswordField

    @FXML
    private lateinit var registerButton: Button

    @FXML
    private lateinit var backToLoginButton: Button


    @FXML
    fun onXXXAction(event: ActionEvent) {

    }
}
```

**Comment by belu** [comment]
@abhinayagarwal @johanvos 
Would you like to see a contribution for this feature?

Had a quick look at the code and could do that together with a refactoring of the SkeletonBuffer to make it simpler and improve readability.
