### ISSUE TITLE
Standalone build

### ISSUE THREAD

**Issue by XakepSDK** [gluonhq/scenebuilder#260]
I'm on arch linux and i would be grateful for standalone build of scene builder without distro-specific installer.

**Comment by bsucker98** [comment]
I second that..Even I'm using another Linux Distro & disappointed...It'd be indeed grateful

**Comment by dddeveloperrr** [comment]
A snap package would be great

**Comment by AlmasB** [comment]
A newer #272 duplicate is open and will be monitored, initial steps to distribute as a snap package are being completed in #458 

This issue is now closed.
