### ISSUE TITLE
Pasting Selected Text in Code Inspector cause duplicate pasting

### ISSUE THREAD

**Issue by SergeMerzliakov** [gluonhq/scenebuilder#263]
JDK:11,12
JavaFX versions: 11,12,13
Operating System Tested:Mac OSX Mojave 10.14.6

How to reproduce:
1. Click on any TextInputControl in UI designer
2.Expand Code Section in Inspector
3. Type in value 'Hello' into any field (OnAction, On Drag Detected and so on)
4. Select the text and paste into any other empty field
5. The test pasted is 'HelloHello'

You can fix the problem by commenting out the paste invocation (not a proposed solution BTW!) in com.oracle.javafx.scenebuilder.app.DocumentWindowController::performPaste.

    private void performPaste() {
        final Node focusOwner = this.getScene().getFocusOwner();
        // If there is FXML in the clipboard, we paste the FXML whatever the focus owner is
        if (getEditorController().canPerformEditAction(EditAction.PASTE)) {
            this.getEditorController().performEditAction(EditAction.PASTE);
            // Give focus to content panel
            contentPanelController.getGlassLayer().requestFocus();
        } else {
            assert isTextInputControlEditing(focusOwner);
            final TextInputControl tic = getTextInputControl(focusOwner);
            // tic.paste();  <====  HACK - PREVENTING PASTE FIXES THE ISSUE!
        }
    }

Somewhere inside  **TextInputControl::paste** it is duplicating the pasted text.
The issue has been around for a while, and has been bugging me, so I will toss my hat into the ring and attempt a fix. 

Wanted to get some feedback first, before attempting my first PR.

1. I have attached a FXML file (with .txt extension) 
2. a screen capture video can be found here - [https://drive.google.com/open?id=1G02417zomzeuwpPckcvVuPUrUY3IS30a](https://drive.google.com/open?id=1G02417zomzeuwpPckcvVuPUrUY3IS30a)

[pastebug_fxml.txt](https://github.com/gluonhq/scenebuilder/files/3981866/pastebug_fxml.txt)

**Comment by Siedlerchr** [comment]
Can still confirm this for the JDK 15
```
Product Version
JavaFX Scene Builder 15.0.0

Build Information
Version 15.0.0
Date: 2020-12-18
Java Version: 15.0.1+9, AdoptOpenJDK

Logging
The default configuration stores logging output in a file named scenebuilder-15.0.0.log (possibly followed by a trailing '.' and a digit).
The default file path is /var/folders/4g/l6q5zzm93vgfhpl64d73nh_h0000gn/T/scenebuilder-15.0.0.log

Java
15.0.1+9, AdoptOpenJDK

Operating System
Mac OS X, x86_64, 10.16
```

**Comment by ryanthara** [comment]
The same behavior here.

Product Version
JavaFX Scene Builder 11.0.0

Build Information
Version 11.0.0
Date: 2019-03-19
Java Version: 11.0.1+13-LTS, Oracle Corporation

Logging
The default configuration stores logging output in a file named scenebuilder-11.0.0.log (possibly followed by a trailing '.' and a digit).
The default file path is /var/folders/cr/kklpm9bd1bsbg8pgyxf7q5gr0000gn/T/scenebuilder-11.0.0.log

Java
11.0.1+13-LTS, Oracle Corporation

Operating System
Mac OS X, x86_64, 10.16

Copyright (c) 2015-2018, Gluon.

https://user-images.githubusercontent.com/7117072/103612446-bdffb180-4f24-11eb-8172-e271083e6991.mp4

**Comment by Puccet** [comment]
Still alive with:
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)

And 

Scene builder 16.0.0

Sigh!

**Comment by HippieStereo** [comment]
Yes I steal have this bug today.
