### ISSUE TITLE
Display issue with SceneBuilder

### ISSUE THREAD

**Issue by djanito** [gluonhq/scenebuilder#273]
I have an issue with the SceneBuilder program.

Everything is going well until the time I reopened the program and the display of the font messed up. Right before, I was trying to set up a font for a button if it helps.

I tried to uninstall/reinstall the program but that didn't solve the problem.

![Screenshot_1](https://user-images.githubusercontent.com/13080926/79133910-1bf3d400-7dad-11ea-9275-d21e586b389b.png)

**Comment by Oliver-Loeffler** [comment]
Could you please describe the exact steps to produce this?
Unfortunately I haven't had much success yet trying to reproduce this on Windows 8.1 (well need to try in Win10).

**Comment by abhinayagarwal** [comment]
This might be due to unsupported locale. @DwaynGFX what locale are you using on the test system?

**Comment by AlmasB** [comment]
Closed due to no response as there are no steps to reproduce this.

**Comment by xhomerly** [comment]
i have en-US locale and have the same problem
![image](https://github.com/gluonhq/scenebuilder/assets/98267479/9d9801e5-8b23-43f1-9df9-77ddac75b57c)
i have just installed it and it was like this. ofc i tried reinstalling, but it didn't help
