### ISSUE TITLE
gluon SceneBuilder 11 does not start

### ISSUE THREAD

**Issue by fdisp** [gluonhq/scenebuilder#282]
environment:
kubuntu 5.4.0-42-generic x86_64 GNU/Linux
JDK: java version "14.0.2" 2020-07-14 (properly set environment variable)
JavaFX: javafx.version=14.0.2.1 
questionable environment variable set
`$PATH_TO_FX`  -> `/usr/lib/jvm/javafx-sdk-14.0.2.1/lib/`

the "runtime" directory located in /opt/SceneBuilder/runtime/ appears intact but **ignored**.
to successfully execute the app i have to execute one of the following commands.

`./gradlew run` in terminal pointed at the root of the source code
or
`java --module-path /usr/lib/jvm/javafx-sdk-14.0.2.1/lib/ --add-modules javafx.web,javafx.fxml,javafx.swing,javafx.media --add-opens=javafx.fxml/javafx.fxml=ALL-UNNAMED -jar /opt/SceneBuilder/app/scenebuilder-11.0.0-all.jar`
in terminal

executing the menu shortcut nothing happens.
when executed from terminal the 
Error: JavaFX runtime components are missing, and are required to run this application

i don't have to deal with this when installing SceneBuilder 2 from oracle.

**Comment by brett-smith** [comment]
I was seeing was I presume is the same problem (using a deb packaged version). When running from the command line, this happens ..

```
/opt/SceneBuilder/SceneBuilder
<JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.
.Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
The folder `/opt/SceneBuilder/runtime//lib/ext` does indeed exist. My work around to this is to move everything in the ext directory into the parent directory, and remove the ext directory entirely. 

```
cd /opt/SceneBuilder/runtime/lib/ext
sudo mv * ..
cd ..
sudo rmdir ext
```

SceneBuilder can now be launched from command line and shortcut. So it looks like the deb build at least is not packaging the runtime correctly.

**Comment by abhinayagarwal** [comment]
This should be fixed in SB-15.  Please download the RC build from https://gluonhq.com/products/scene-builder/
