### ISSUE TITLE
Gluon support?

### ISSUE THREAD

**Issue by treilhes** [gluonhq/scenebuilder#285]
Does Gluon still support the development of SceneBuilder ? Maintenance mode only? Discontinued?

**Comment by sfxcode** [comment]
It seems like there is no active development in the last months ... I also like to know about the actual state of this project

**Comment by johanvos** [comment]
Scene Builder is an open source project, so everyone can contribute to it. Gluon makes sure that it keeps working with the latest JavaFX and Java releases. If there are circumstances that require a new build, we do that.
The focus is on making sure everything is still working with new releases, and therefore we heavily use Scene Builder as a regression test in the OpenJFX development.
There are many downloads of Scene Builder and it is actively being used by many developers. We have no plans to discontinue it.

**Comment by treilhes** [comment]
Hello @johanvos,
Thanks for your feedback. So it's maintenance mode....
So what about pull requests? Can we expect adding new features to scene builder apart bug fixes and features related to the Gluon library?

**Comment by abhinayagarwal** [comment]
All PRs are accepted and more than welcome! 💯

Gluon has been trying to streamline community contributions and make it easier for anyone to contribute. We have recently added issue and PR templates (#313) to the repository and a contribution doc is in the making under #307.

We are aware that we have been slow in the past. However, we are hopeful that with all the changes we are doing, we will be able to help community with their issues and review PRs faster.
