### ISSUE TITLE
Program freezes when attempting to close it

### ISSUE THREAD

**Issue by QazCetelic** [gluonhq/scenebuilder#290]

**Comment by Oliver-Loeffler** [comment]
Hi! Could you please further specify the issue?

Which system platform (Windows, Mac, Linux)?
Is the issue reproducible or random?

Are there steps to reproduce the problem?

Thanks.

**Comment by QazCetelic** [comment]
I'm using the Linux distribution KDE Neon which is based on Ubuntu LTS but with KDE Plasma as desktop environment.
Here's [a video in which I'm clicking on several parts of the UI](https://youtu.be/z2fibT5dlVw)

```
Operating System: KDE neon 5.20
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.4.0-62-generic
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-8750H CPU @ 2.20GHz
Memory: 16 GB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 630
```

**Comment by Oliver-Loeffler** [comment]
Thanks for sharing this. I will try to reproduce this with a recent KDE neon installation (in a VM).

**Comment by QazCetelic** [comment]
I don't remember setting it, so I think I used the default.

**Comment by QazCetelic** [comment]
> Thanks for sharing this. I will try to reproduce this with a recent KDE neon installation (in a VM). Which Java and JavaFX version did you use?

Were you able to reproduce the issue?

**Comment by Oliver-Loeffler** [comment]
Thanks for pinging me. Well, as of now I was not able to reproduce this. Have you tried newer versions of SceneBuilder? It's possible that versions 18 and 19 no longer suffer this issue.

**Comment by QazCetelic** [comment]
I'm unable to replicate the issue with the Flatpak of version 19 on Fedora 37
