### ISSUE TITLE
[Feature request]: build Scenebuilder as a Flatpak application

### ISSUE THREAD

**Issue by rickytower** [gluonhq/scenebuilder#293]
Flatpak is the feature of packaging software in GNU/Linux operating systems because it gives you the advantage of containerizing applications in a standard format and run indipendendently from the host setup.
I think it could be great to have Scenebuilder as a Flatpak application so, in that way, every single Linux user can use it without worring about system requirements.

**Comment by ghazyami** [comment]
Scene Builder is now available on Flathub.
@batashi did the original work, I followed up afterwards.

If any of the `Scene Builder` maintainers would like to be part of maintains the flatpak, please reach out!

Flathub manifest: https://github.com/flathub/com.gluonhq.SceneBuilder
Flathub link: https://flathub.org/apps/details/com.gluonhq.SceneBuilder
Flathub badge: `<a href='https://flathub.org/apps/details/com.gluonhq.SceneBuilder'><img width='240' alt='Download on Flathub' src='https://flathub.org/assets/badges/flathub-badge-en.png'/></a>`
Flathub badge sample:
<a href='https://flathub.org/apps/details/com.gluonhq.SceneBuilder'><img width='240' alt='Download on Flathub' src='https://flathub.org/assets/badges/flathub-badge-en.png'/></a>

**Comment by AlmasB** [comment]
This seems to be implemented as part of #559

**Comment by batashi** [comment]
Thanks @ghazyami  For your efforts. 

@AlmasB  it's better to be part of this project and maintain under the upstream project.
