### ISSUE TITLE
Scene builder in Intellij IDEA sometimes works, sometimes doesn't

### ISSUE THREAD

**Issue by Yato333** [gluonhq/scenebuilder#296]
When I open an FXML file in Intellij and press the Scene Builder button, sometimes it shows as on the following picture.
Sometimes it fixes itself by restarting the IDE and sometimes some FXML files open, some files don't. For example the next file opened in IDE - table.fxml works fine.

![Screenshot_2](https://user-images.githubusercontent.com/29233962/100726053-1d6e1d00-33cd-11eb-9c17-72f52ba20be4.png)

**Comment by treilhes** [comment]
Hello @Yato333,
Can you open the same file in the standalone version of SceneBuilder ?
What happen?

**Comment by Yato333** [comment]
I realised what the issue is.
 Apparently it refuses to open because the file contains a line equialent to this:

`<derivedClass fx:id="derivedClassObject"/>` 

where `derivedClass` is a class derived from JavaFX `ChoiceBox` class.
The problem fixes itself when this line is removed.

**Comment by Yato333** [comment]
@treilhes It opens and marks those derived classes as invalid, I guess. (see previous comment)
![image](https://user-images.githubusercontent.com/29233962/100728666-81deab80-33d0-11eb-9515-f71ce52f4ca1.png)

**Comment by treilhes** [comment]
It means the fxml file use custom controls. You need to load the jar file containing thos custom controls into the SceneBuilder Library. I don't know how to do it in IntelliJ but the same approach must be taken.
