### ISSUE TITLE
Context menus in some textfields are empty, Scene Builder's 11 left accordion

### ISSUE THREAD

**Issue by UltraBurstXD** [gluonhq/scenebuilder#308]
Context menu is empty in some textfields, especially in **code** accordion, Ubuntu 20.10.

**Comment by abhinayagarwal** [comment]
Hi @UltraBurstXD,

Thank you for opening this issue.

Unfortunately, as the issue doesn't have enough information, I will have to close it.

If you want to provide any additional information, please add a comment and we will re-open it.
