### ISSUE TITLE
SceneBuilder 15.0.1 doesn't start

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [gluonhq/scenebuilder#323]
I've just donwloaded fresh SceneBuilder-15.0.1.msi and after installing nothing happens when exe file is executed. When run from console no output is produced (e.g. stacktrace).
The installation folder is C:\Program Files\SceneBuilder
Can I somehow determine if the version in MSI is really the latest version after recent fix of similar issue, https://github.com/gluonhq/scenebuilder/issues/316?

**Comment by jan-tosovsky-cz** [comment]
However, I could execute the app using this command
```
cd "C:\Program Files\SceneBuilder"
runtime\bin\java --add-opens=javafx.fxml/javafx.fxml=ALL-UNNAMED --module-path=C:\javafx-jmods-15.0.1 -jar app\SceneBuilder-15.0.1-all.jar
```
There is no `mod` folder bundled so I used that in my drive.

**Comment by palexdev** [comment]
It eventually opens but compared to the old version it waaaay slower

**Comment by Oliver-Loeffler** [comment]
Hi!
can you please check the effective `java.library.path` on your system?
It is possible, that in case of a 2nd installed JVM, there might be a situation where certain runtime libraries are not properly resolved (e.g. wrong version is used). With Java 8 this can lead to a crash, cannot say yet, how this behaves, when mixing other JVMs beside Java8.

This works as follows on a Windows Command Line:
```
java -XshowSettings:properties
```

Output is (on my machine):
```
C:\Program Files\AdoptOpenJDK\jdk-13.0.2.8-hotspot\bin>java -XshowSettings:properties
Property settings:
    file.encoding = Cp1252
    file.separator = \
    java.class.path =
    java.class.version = 57.0
    java.home = C:\Program Files\AdoptOpenJDK\jdk-13.0.2.8-hotspot
    java.io.tmpdir = C:\Users\Username\AppData\Local\Temp\
    java.library.path = C:\Program Files\AdoptOpenJDK\jdk-13.0.2.8-hotspot\bin
        C:\WINDOWS\Sun\Java\bin
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\Temp
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 13.0.2+8
    java.specification.name = Java Platform API Specification
   [...lot more comes here...]
```

**Comment by Oliver-Loeffler** [comment]
This is most likely closed with PR #358. 
#358 defines a library path only for SceneBuilder and avoids that the system default (Windows path as defined in environment) is used.

**Comment by palexdev** [comment]
> This is most likely closed with PR #358.
> #358 defines a library path only for SceneBuilder and avoids that the system default (Windows path as defined in environment) is used.

Yes, I can confirm that it works good now

**Comment by palexdev** [comment]
Oh I didn't know that
I ended up building an msi myself and install the new version
I had to run the commands manually in CMD but I did it

**Comment by Oliver-Loeffler** [comment]
Ah, I did this today, up to now I had no idea where to park the test packages. Eventually I'll drop the test branch.
Also, I was now able to reproduce the issue with IntelliJ and it seems, it was the very same mechanism.
Unfortunately, if not defined specifically, the provided JVM takes everything wich is on the Windows environment path and this depends on each individual machine/user setup. Actually, for me, this feels also like kind of a security thing to be aware of.

**Comment by AlmasB** [comment]
@jan-tosovsky-cz please can you update us on whether this issue is resolved with newer versions of Scene Builder, thanks.

**Comment by jan-tosovsky-cz** [comment]
@AlmasB I've just tried 17.0.0 and it works like a charm.

**Comment by AlmasB** [comment]
Brilliant, thanks!
