### ISSUE TITLE
The "Installed Libraries/FXML Files window" should show a sorted list.

### ISSUE THREAD

**Issue by joehei** [gluonhq/scenebuilder#324]
### Expected Behavior
The "Installed Libraries/FXML Files window" shows a list of currently imported fxml and jar files, this list is unsorted and therefore difficult to read.

### Current Behavior
The window should show a sorted list so that libs with the same group ID are shown together.

### Context
This should make it easier to identify is one artifact is missing e.g. when using ikonli font icons which consist of several artifacts.

**Comment by Oliver-Loeffler** [comment]
There are different types of libraries, there are:

* any folder folder wit ``*.class` files
* any JAR or FXML file from file system
* any dependency from a given repository with Maven coordinates such as 'groupId:artifactName:artifactVersion'

My proposal to this is:
* show folders first (folders sorted alphabetically, using the Java built-in Path comparator)
* then show individual JAR files (also using Java build-in Path comparator)
* then show all libraries from repositories sorted alphabetically by their Maven coordinates

Example:
![SceneBuilder_LibrariesListSortingProposal](https://user-images.githubusercontent.com/22102800/113191818-4ceb4400-925e-11eb-8c52-ca91badcc7dd.png)

What do you think?

**Comment by abhinayagarwal** [comment]
This approach looks good to me :+1:

**Comment by joehei** [comment]
Looks good :-)
