### ISSUE TITLE
Text truncated in new version dialog

### ISSUE THREAD

**Issue by abhinayagarwal** [gluonhq/scenebuilder#333]
For each new version, a dialog is shown to all our users. The text in this dialog is truncated.

### Expected Behavior

Text shouldn't be truncated inside the dialog

### Current Behavior

Text is truncated for "Current Version" and for the description of release.

### Steps to Reproduce

Always reproducable

### Your Environment

Ubuntu 20.04.2

### Screenshots

![image](https://user-images.githubusercontent.com/3197675/110930416-17ce8e80-834f-11eb-904e-adfded40ee4c.png)

**Comment by Oliver-Loeffler** [comment]
On Windows this dialog looks as follows:

* no truncation
* instead a line wrap is added
* text is displayed below the dialog graphic

![SceneBuilderVersionDownload](https://user-images.githubusercontent.com/22102800/113180308-e14eaa00-9250-11eb-834b-57891a157efa.PNG)

**Comment by abhinayagarwal** [comment]
Hi @Oliver-Loeffler ,

This may be a platform related issue. For more information: https://bugs.openjdk.java.net/browse/JDK-8258664

**Comment by Oliver-Loeffler** [comment]
Thanks for the link - yes, just found this out by testing. Works all fine with any combination of JavaFX11 ... 16 and JDK11 ... 16 on Windows. DPI Scaling ... haven't tested that yet. Thanks!

**Comment by abhinayagarwal** [comment]
May be a linux only issue.

Can you also test with JavaFX 15? https://bugs.openjdk.java.net/browse/JDK-8199592 was recently fixed in JavaFX 16.

**Comment by Oliver-Loeffler** [comment]
Did the test run help? Any news on this topic?

**Comment by abhinayagarwal** [comment]
Hi @Oliver-Loeffler ,

Thanks for the nudge, I somehow missed your comment with the test results.

As the issue could not be reproduced on Windows, it is most probably a Linux/Ubuntu specific issue. I will try to create a SSCCE and file it in the JBS for the OpenJFX team.

**Comment by abhinayagarwal** [comment]
While trying to create a SSCCE, I found that DialogPane has a label and it sets the following properties on it:

```
static Label createContentLabel(String text) {
    Label label = new Label(text);
    label.setMaxWidth(Double.MAX_VALUE);
    label.setMaxHeight(Double.MAX_VALUE);
    label.getStyleClass().add("content");
    label.setWrapText(true);
    label.setPrefWidth(360);
    return label;
}
```

While in Scene Builder, the update label has the following styles:

```
.download_scenebuilder-dialog .main-container > .latest-version-text {
    -fx-max-width: 420;
    -fx-wrap-text: true;
}
```

Changing the above to the following fixed the issue:

```
.download_scenebuilder-dialog .main-container > .latest-version-text {
    -fx-pref-width: 420;
    -fx-max-width: Infinity;
    -fx-wrap-text: true;
}
```

The current version label was getting truncated because the GridPane in `UpdateSceneBuilderDialog` had a column constraint on it setting the width:

```
gridPane.getColumnConstraints().add(new ColumnConstraints(100));
```

Removing it fixed the truncated label issue for "Current Version"

**Comment by Oliver-Loeffler** [comment]
Thanks for the analysis!
