### ISSUE TITLE
User library - import classes from classpath

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#34]
Originally reported by: **Luca Domenichini (Bitbucket: [mimmoz81](https://bitbucket.org/mimmoz81), GitHub: [mimmoz81](https://github.com/mimmoz81))**

----------------------------------------

Currently, the user library has a limited approach in loading custom components.
Only jars and fxml are scanned in library folder.
If SB is used to work in many different projects with different custom components, it is necessary to replace the library jars every time one needs to switch the workspace.

I think it would be very useful to have SB to scan the classpath too (this means, JARs and directories). In this way, one could launch SB appending to its classpath its current working directory and other jars as well, without having the need to package a jar "just for SB". IDEs too (think Eclipse), could launch SB appending to the classpath the current workspace and having SB to nicely have all the custom controls loaded directly from user the workspace.

I'm going to pull a request the does implement this issue shortly..
Please comment and fill in ideas..

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/34

**Comment by mimmoz81** [comment]
this issue can closed with PR #228 merged
