### ISSUE TITLE
Set CSS-ID automatically while setting the fx:id

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#35]
Originally reported by: **Przemyslaw Tarasewicz (Bitbucket: [przemyslawt](https://bitbucket.org/przemyslawt), GitHub: Unknown)**

----------------------------------------

It is sometimes convenient to set the css-id automatically while setting the fx:id. One use case would be the automated UI testing. You could then have the same names for the fx:id and the CSS-ID without the need to switch to the other section and type the name for the id again. Please see the attached images.

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/35

**Comment by AlmasB** [comment]
This feature's use case is too specific. As it stands, there is no clear benefit to a typical user, hence it is closed.
