### ISSUE TITLE
Popup with failed Update Check in Dev Mode

### ISSUE THREAD

**Issue by belu** [gluonhq/scenebuilder#352]
When starting SceneBuilder locally from master an error popup for a failed "Update Check" is shown.
It states in the text that this is probably due to "Version number format not supported. Maybe using SNAPSHOT or RC versions".
If starting SceneBuilder frequently this gets annoying.
Additionally, the main window size changes and is smaller when the popup shows up.

### Expected Behavior
No error popup is shown. The main window size is not changed.

### Current Behavior
An error popup "Update check" is shown. The main window size is reduced.

### Steps to Reproduce
1. Start SceneBuilder with `mvn javafx:run -f app`.
2. Close the window with the recent FXML files opened (title "Gluon Scene Builder").
3. Error popup should appear. Size of the main window is changed.
 
### Your Environment
SceneBuilder built from master
Linux

### Screenshots
![scenebuilder_update_check](https://user-images.githubusercontent.com/1174164/113814828-864a1500-9772-11eb-976a-3096b10ff5a6.png)

**Comment by Oliver-Loeffler** [comment]
What do you think about following approaches for dev version:

* Accept snapshot and rc versions, extract the version without suffix and make the update check.
* OR: Skip the update check at program start, don't show any notification; Perform update check only on demand (called from menu), show same error.
* OR: Skip the update check at program start, don't show any notification; Perform update check only on demand (called from menu), permit update check on RC or SNAPSHOT versions in a dev environment.

**Comment by belu** [comment]
Skipping the update check at program start - at least in Dev mode - sounds good to me.

In Dev mode you normally wouldn't check for updates. Therefore IMHO it is not necessary to change the current behaviour on how to extract the version.

**Comment by belu** [comment]
IMHO what should be fixed is the resizing of the main window when the update-check popup dialog appears.

Just tested with SceneBuilder 15.0.1 (non-dev mode) when an update is available ("Your Scene Builder version isn't the latest.").

**Comment by abhinayagarwal** [comment]
I have a created a fix for not showing the update dialog in case of development mode and forked out the second issue of main window resize into a separate issue.
