### ISSUE TITLE
SceneBuilder doesn't open or it's really slow in IntelliJ

### ISSUE THREAD

**Issue by palexdev** [gluonhq/scenebuilder#354]
### Expected Behavior
When I open SceneBuilder from any shortcut it opens almost immediately.

### Current Behavior
In IntelliJ, it requires some time to open, it's really slow.

### Steps to Reproduce

1. Right-click on a fxml file
2. Click on "Open In SceneBuilder"

### Your Environment
OS: Windows 10 20H2 x64, SceneBuilder v16.0.0, IntelliJ IDEA 2021.1

### Additional Details
I submitted an issue on JetBrain's YourTrack and they said that it is a third-party problem.
Link to the issue: [YourTrack](https://youtrack.jetbrains.com/issue/IDEA-266297)

**Comment by abhinayagarwal** [comment]
Hi @palexdev !

Thank you for opening this issue.

Do you have the same experience in NB and Eclipse?

**Comment by palexdev** [comment]
Just tested on a VM, both NB and Eclipse work fine. SceneBuilder opens immediately.
I was wondering if the problem could be the javafx plugin for intellij at this point

**Comment by palexdev** [comment]
@abhinayagarwal is it possible to enable logging or is it already enabled?
I noticed that if I restart the process with a process manager SceneBuilder opens immediately (the files is loaded too)
Could it be some JVM exception that slows it down?

**Comment by palexdev** [comment]
https://user-images.githubusercontent.com/16880178/125312560-ad495180-e334-11eb-8688-eb394a5cc99e.mp4

Video of the actual behavior

**Comment by palexdev** [comment]
Closing as fixed by #358
But at the time of writing this, the latest SceneBuilder build available still doesn't have the fix, so you either wait for the new version or compile it by yourself (good luck with that)
