### ISSUE TITLE
Gradle 7 Compatibility

### ISSUE THREAD

**Issue by lorenzleutgeb** [gluonhq/scenebuilder#356]
Building this project with [Gradle 7](https://docs.gradle.org/7.0/release-notes.html) fails. The output can be found in [this gist](https://gist.github.com/r-rmcgibbo/e5090b647c72fa9cca2b8963a1671fd4).

The project makes use of the `maven` plugin, which was removed. Instead `maven-publish` [should be used](https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin).

**Comment by abhinayagarwal** [comment]
We have moved from Gradle to Maven.
