### ISSUE TITLE
StartupWMClass entry missing from desktop file

### ISSUE THREAD

**Issue by abhinayagarwal** [gluonhq/scenebuilder#359]
Desktop name for Scene Builder on Ubuntu is displayed as "com.oracle.javafx.scenebuilder.app.SceneBuilderApp" instead of "Scene Builder". 

The following entry for `StartupWMClass` in the `/usr/share/applications/scenebuilder-SceneBuilder.desktop` should be added to fix this:

```
StartupWMClass=com.oracle.javafx.scenebuilder.app.SceneBuilderApp
```
However, since we package the application using `JPackage`, we need to find out how to achieve this using JPackage.

### Expected Behavior
Application name on the title bar should be "Scene Builder"

### Current Behavior
Application name on the title bar is shown as "com.oracle.javafx.scenebuilder.app.SceneBuilderApp"

### Steps to Reproduce
Download, install and run the application on Ubuntu 20.04

### Your Environment
Ubuntu 20.04

### Screenshots
![image (3)](https://user-images.githubusercontent.com/3197675/115336539-0b92e800-a1bd-11eb-9401-4542d1b5c421.png)

**Comment by Oliver-Loeffler** [comment]
I have played around with `jpackage` and also reviewed its [source code](https://github.com/openjdk/jdk/blob/master/src/jdk.jpackage/linux/classes/jdk/jpackage/internal/DesktopIntegration.java). Not sure yet, but I think there is no chance to achieve this with `jpackage` as of now.

But, we could achieve this via Github Actions. It is possible to re-pack a Debian package.
It works as follows (might require installation of tree command):

```sh
cd ~/scenebuilder

# prepare directories
mkdir -p repackaged jpackaged/DEBIAN

# extract the existing deb file into jpackaged directory
dpkg-deb -X app/target/install/scenebuilder_16.0.0-1_amd64.deb jpackaged/

# append the one StartupWMClass to the desktop file
echo StartupWMClass=com.oracle.javafx.scenebuilder.app.SceneBuilderApp >> jpackaged/opt/scenebuilder/lib/scenebuilder-SceneBuilder.desktop

# prepare the repackaging
dpkg-deb -e app/target/install/scenebuilder_16.0.0-1_amd64.deb jpackaged/DEBIAN

# create a all new package
dpkg-deb -Z xz -b jpackaged/ repackaged/
```

This will require some adjustments to work with the Github Actions environment variables but basically for Debian files this shall do.

**Comment by Oliver-Loeffler** [comment]
I found a possibly better solution. JPackage offers to use template for certain phases of the installation. For Debian there is a `postinst` script which can be utilized. Within this script the desktop file is installed and prior to its installation one can add the line `StartupWMClass=com.oracle.javafx.scenebuilder.app.SceneBuilderApp`. The PR is going to be reworked in order to offer the more simple solution for this issue.

**Comment by Oliver-Loeffler** [comment]
With the modification proposed in PR #407, SceneBuilder on Ubuntu, installed from a *.deb package, looks as follows:

![unknown_2021 09 08-11 24_1_copped](https://user-images.githubusercontent.com/22102800/132483771-e02351e3-a6c3-4768-b759-a594045da9ab.gif)

Thanks for providing the hint with the `StartupWMClass` setting.
