### ISSUE TITLE
JFXTextField not rendering 

### ISSUE THREAD

**Issue by chege-maina** [gluonhq/scenebuilder#361]
When I drag the JFXTextField it goes back to the list and does not appear on the scene.... If I add it manually on the fxml code the entire scene does not render.... Using Scenebuilder 16
![scenebuilder](https://user-images.githubusercontent.com/79351719/120002572-a2816a00-bfdd-11eb-9725-fdc6b700a33a.png)

**Comment by palexdev** [comment]
Probably because it's not compatible with recent versions of JavaFX
Try my project instead: [MaterialFX](https://github.com/palexdev/MaterialFX)

**Comment by Tareq57** [comment]
This is the same problem I am facing. and my current version of scene builder is also 16. But I searched on the internet and found that jfoenix is not working properly in the JavaFX 11+ version.

**Comment by abhinayagarwal** [comment]
This is not a Scene Builder issue. Please report in library repository.

**Comment by Tareq57** [comment]
But I solved this problem by changing the version of scene builder from 16 to 11. cause I have read a post in stackoverflow. I am giving you this link: https://stackoverflow.com/questions/55889654/illegalaccessexception-for-jfxtextfield-with-java-sdk-12.

**Comment by chege-maina** [comment]
> But I solved this problem by changing the version of scene builder from 16 to 11. cause I have read a post in stackoverflow. I am giving you this link: https://stackoverflow.com/questions/55889654/illegalaccessexception-for-jfxtextfield-with-java-sdk-12.

Thanks very helpful.
