### ISSUE TITLE
Scenebuilder 16 doesn't start on Linux Mint

### ISSUE THREAD

**Issue by gringofe** [gluonhq/scenebuilder#362]
I installed version `16.0.0` using the deb binary from the Gluon website.

### Expected Behavior
Scenebuilder starts when user launches it

### Current Behavior
Scenebuilder doesn't start; when launched from commandline, the following log is printed:
```
May 30, 2021 1:33:31 PM com.oracle.javafx.scenebuilder.app.SceneBuilderApp logTimestamp
INFO: JavaFX Scene Builder started
```

### Steps to Reproduce
1. Install deb on Linux Mint
2. Try to launch

### Your Environment
* `Linux Mint 19.3`
* `OpenJDK 11.0.11`

**Comment by ennerf** [comment]
Possibly the same issue as on Windows #366

**Comment by abhinayagarwal** [comment]
Hi @gringofe ,

If you have already ran `/opt/scenebuilder/bin/SceneBuilder` and haven't seen any logs, can you try the following command and check if you can get any information:

```
/opt/scenebuilder/lib/runtime/bin/java -jar /opt/scenebuilder/lib/app/SceneBuilder-16.0.0-all.jar
```

**Comment by Oliver-Loeffler** [comment]
Please try also to run: `/opt/scenebuilder/lib/runtime/bin/java`-XshowSettings:properties` and pleas post the contents of following lines:

* `java.class.path`
* `java.library.path`

It seems, that at least `java.library.path` has the potential to prevent an application or a JVM from launch. For Windows the issue is reproducible, for Linux the boundary conditions have not been found so far. I tried to reproduce the issue on Linux Mint 19.3 in a fresh VM with OpenJDK 11.0.4 installed and failed. Will now attempt 11.0.11 and then also with JavaFX installation.

**Comment by Oliver-Loeffler** [comment]
One idea to test.
SceneBuilder installs by default into `/opt/scenebuilder`. There is supposed to be a file `/opt/scenebuilder/lib/app/SceneBuilder.cfg`. Within this file, a section `[JavaOptions]` may exist.

You might add one additional line to this section and attempt a restart of SceneBuilder as described above.

```cfg
[JavaOptions]
java-options=-Djava.library.path=/opt/scenebuilder/lib/runtime/lib:/opt/scenebuilder/lib/runtime/bin
```

If SceneBuilder starts after this modification, the issue can be solved for future releases by a modification of the jpackage script.

**Comment by abhinayagarwal** [comment]
@Oliver-Loeffler 

> Is it possible to create a DEB file for testing?

Sure, just use the jpackage command from GA scripts.

> I have created one but, I am hesitating to upload it here. Would it be okay to upload here?

In this issue, right? I do not see any problem with uploading the deb. FYI, executables are not supported to be uploaded in Githuib issues. You can however try to upload a zip file instead. 

As the issue hasn't been reproducible on my end, it is difficult to concur if the proposed fix actually fixes OP's issue.

**Comment by Oliver-Loeffler** [comment]
Hello @gringofe ,

you might want to try out a test build. 
It's created from current master and the difference is, that now the library path is limited to the installation directory.

[https://github.com/Oliver-Loeffler/scenebuilder/blob/issue-362-deb-test/testbuilds/scenebuilder_16.0.0-SNAPSHOT-issue-
362_amd64.deb]()

Please try out and it would be great if you could post the contents of the "Help/About Scene Builder" dialog.

**Comment by gringofe** [comment]
Hi,

I don't know what the issue was, but it works fine now? Can't reproduce it anymore

**Comment by Oliver-Loeffler** [comment]
@gringofe Did you try the package for testing or did you repeat the test with the SB version you have had installed?
