### ISSUE TITLE
SceneBuilder 16 does not start on Windows 10

### ISSUE THREAD

**Issue by ennerf** [gluonhq/scenebuilder#368]
I installed the Scene Builder 16.0.0 installer on Windows 10.0.19043, but it won't execute.

### Current Behavior
SceneBuilder does not start. 

### Steps to Reproduce

It looks like a JVM issue. Trying to run the JVM from commandline yields:

```shell
<...\AppData\Local\SceneBuilder>runtime\bin\java -version
<JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.
.Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

### Workaround

Renaming the `runtime\lib\ext` directory to `ext2` lets both `java` and `SceneBuilder.exe` execute:

```shell
<...\AppData\Local\SceneBuilder>runtime\bin\java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode)
```

I also added the renamed directory to the classpath via editing the `SceneBuilder.cfg` file:

```shell
app.classpath=$APPDIR\scenebuilder-16.0.0-all.jar;$APPDIR\..\runtime\lib\ext2\*
```

It's hard to verify whether the classpath works properly, but this runs and I haven't run into any errors yet.

**Comment by abhinayagarwal** [comment]
I installed Scene Builder on Windows 64-bit OS build 19043.1081. However, there is no `ext` directory in `SceneBuilder\runtime\lib`.

Can you add the text from Scene Builder -> Help -> About Scene Builder?

**Comment by ennerf** [comment]
Sorry, it looks like an older version wasn't uninstalled correctly and left some remnants. A clean install works.
