### ISSUE TITLE
Log files are not created

### ISSUE THREAD

**Issue by abhinayagarwal** [gluonhq/scenebuilder#370]
The About dialog mentions that the log file must be created in tmp directory. However, no log files are created.

This is because no log file config is loaded by Scene Builder.

### Expected Behavior

Log file should be generated when Scene Builder runs.

### Current Behavior

No log files are generated

### Steps to Reproduce

Run Scene Builder on any platform and no log files are created.

**Comment by credmond** [comment]
No logs on Windows, verified in version 20.

Product Version
JavaFX Scene Builder 20.0.0

Build Information
Version 20.0.0
Date: 2023-05-08 14:08:52
JavaFX Version: 20.0.1
Java Version: 20, OpenJDK Runtime Environment

Logging
The default configuration stores logging output in a file named scenebuilder-20.0.0.log (possibly followed by a trailing '.' and a digit).
The default file path is C:\Users\zzz\.scenebuilder\logs\scenebuilder-20.0.0.log

JavaFX
20.0.1

Java
20.0.1, OpenJDK Runtime Environment
