### ISSUE TITLE
Bring back Gradle

### ISSUE THREAD

**Issue by palexdev** [gluonhq/scenebuilder#375]
Project can't be built with Maven
This is the messy output: [Pastebin](https://pastebin.com/pT0cjcRi)

Bring back Gradle, it's way easier to manage

**Comment by abhinayagarwal** [comment]
The tests seem to be failing on Windows. I can have a look later.

For now, can you try the following:

```
mvn install -DskipTests && mvn javafx:run -f app
```

**Comment by johanvos** [comment]
I think the output is pretty clear :)
The worrying thing though is that there are test failures on Windows. That should not happen (independent of using maven/gradle/commandline/...) so we have to fix that, and we have to include Windows tests in our CI system to make sure it doesn't happen again (after this is fixed)

```
[ERROR] Tests run: 4, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 0.662 s <<< FAILURE! - in com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest
[ERROR] com.oracle.javafx.scenebuilder.kit.skeleton.SkeletonBufferJavaTest.skeletonToString_testFxml_full_withComments  Time elapsed: 0.584 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<...import java.net.URL;[
import java.util.ResourceBundle;
import javafx.fxml.FXML;
import javafx.scene.control.TableView;
import javafx.scene.input.MouseEvent;
]
 
public class Empt...> but was:<...import java.net.URL;[
import java.util.ResourceBundle;
import javafx.fxml.FXML;
import javafx.scene.control.TableView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.VBox;]
 
public class Empt...>

```

**Comment by abhinayagarwal** [comment]
I had a quick look and it looks like the tests added in https://github.com/gluonhq/scenebuilder/pull/328 are breaking on Windows due to incompatible line-breaks in the text files.

I will file a separate issue for this and close this.
