### ISSUE TITLE
Tests are broken on Windows

### ISSUE THREAD

**Issue by abhinayagarwal** [gluonhq/scenebuilder#376]
Tests introduced in #328 are breaking on Windows due to incompatible line-breaks in the text files.

### Expected Behavior
All tests should pass on all platforms

### Current Behavior
Tests fail on Windows

### Steps to Reproduce
1.  Get your hands on a Windows machine
2. Checkout scenebuilder
3. Run `mvn verify`

### Your Environment
Windows 10 + JDK 11

### Screenshots
NA

**Comment by abhinayagarwal** [comment]
@belu Can you can have a look?

**Comment by Oliver-Loeffler** [comment]
Hi!
I just checked out scenebuilder and cannot reproduce the issue.
I am using Java 11.0.2 (AdoptOpenJDK) on Win 10 Pro 21H1.

**Comment by abhinayagarwal** [comment]
Hi @Oliver-Loeffler,

Thanks for your feedback. This issue is present and reproducible. Please check [this Github Actions job](https://github.com/abhinayagarwal/scenebuilder/runs/3163394027?check_suite_focus=true).

I spent some time trying to figure out what was going on and it turns out that a [recent commit](https://github.com/gluonhq/scenebuilder/commit/2ab807a0253a95d62d2376d0336e72a8958c9309#diff-0d03d25c4354d83495020d140ffb31145769d5538a5a3a40420351376a4f4356R43) introduced system specify new line character in FXML skeleton creator. I scanned throughout Scene Builder repository and every where `\n` is used.

Updating `System.lineSeparator();` to `\n` fixes the issue for all OSes.

**Comment by Oliver-Loeffler** [comment]
Hi @abhinayagarwal , it was my mistake.
But, as of now I am preparing a PR for review.
The root cause is, that Windows uses `\r\n` and Linux uses `\n` for line endings. I've made 3 relatively small changes to mitigate the problem.

**Comment by abhinayagarwal** [comment]
The question here is if the implementation for FXML creation correct? If yes, then changing the tests makes sense. If not, we may need to fix the implementation.

**Comment by Oliver-Loeffler** [comment]
True. As far as I can oversee it now, all subclasses of `AbstractSkeletonCreator` use the system provided line separator (`System.lineSeparator()`) which is fine in my opinion.

I will need to run the test on Linux tomorrow to see how it works there. I think that for `SkeletonBufferTest` the modification of the test is okay, as it now uses also the system provided line separator, same as the SkeletonBuffer implementations. 
For the other classes its somehow different.

May be it's good to reshape the AbstractSkeletonBuffer so, that one can pass the desired line separator into the constructor.
If okay, I will create a proposal.

**Comment by abhinayagarwal** [comment]
Tests seems to be running well on GIthub Actions with latest code, but the same fail on my local windows machine. @Oliver-Loeffler Have you faced this issue recently?

**Comment by Oliver-Loeffler** [comment]
Hi @abhinayagarwal , no, I haven't faced this issue recently. The issue should not occur, when you clone Scene Builder from Github freshly. Nevertheless, in recent past I figured out to avoid conflicts with Git line ending behavior.
In fact, it's better to replace line endings in test case files  after loading with what is expected and override what was checked in or what Git provides.

But to get some certainty, would be so kind and try to make a fresh clone of Scene Builder from GH master into a new directory? Please try that.

In between, I'll file an issue and a corresponding PR to avoid recurrence eventually.

**Comment by abhinayagarwal** [comment]
Hi @Oliver-Loeffler ,

Fresh clone did the trick. Thanks a ton 👍
