### ISSUE TITLE
Update build workflow to run across all major platforms

### ISSUE THREAD

**Issue by abhinayagarwal** [gluonhq/scenebuilder#378]
It is important to test all PRs against all 3 major platforms to avoid issues like #376 

My recommendation is to convert the build workflow to run across a matrix of latest oses.

**Comment by Oliver-Loeffler** [comment]
@abhinayagarwal As this workflow is now working, have you considered to run more frequent releases? As of now there is only the release in March/September. 

How about setting up something like monthly releases or even something like a nightly? May be monthly is enough, master does not change that often. But actually, for the users it would be a benefit and we would get earlier feedback on issues.
