### ISSUE TITLE
Save As Button In Preview Sample Controller Skeleton Dialog

### ISSUE THREAD

**Issue by kado** [gluonhq/scenebuilder#381]
Add a button to save the generated Controller Skeleton to a java file. 
### Expected Behavior
When the "Save As" button is clicked, SceneBuilder should prompt the Save Dialog to user select a path and filename. Generated java controller skeleton must be saved as .java file.

### Current Behavior
Button does not exist

### Context
Now working and teaching JavaFx with VSCode. These feature would save time a lot time and will easy up things for students.

Thanks!

**Comment by Oliver-Loeffler** [comment]
Hi @kado!

I have prepared a PR for this issue. The functionality is now as follows:
* The controller skeleton preview as now a "Save as" button.
* When pressed a file name is proposed.
* When confirmed with "save", the skeleton is saved to the proposed file.
* A confirmation dialog is shown, which allows to copy the file path to the clipboard.

I've explored following use cases for that (assuming now that Java has been chosen as language of preference):

| # | Use case | FXML status | Controller class definition | File Name Proposal |
|-|-|-|-|-|
| 1 | Fresh project | FXML not saved | not specified                           |  `~/PleaseProvideControllerClassName.java` |
| 2 | Fresh project | FXML not saved | set to `MyCustomController`  |  `~/MyCustomController.java` |
| 3 | Fresh project | FXML saved (e.g. `/Temp/SceneBuilder/Test.fxml`)  | not specified | `/Temp/SceneBuilder/TestController.java` |
| 4 | Fresh project | FXML saved (e.g. `/Temp/SceneBuilder/Test.fxml`)  | `MyFancyApp$NestedController` | `/Temp/SceneBuilder/NestedController.java` |
| 5 | Existing project | FXML opened from 'src/main/resources/.../View.fxml' | no controller specified | 'src/main/java/.../ViewController.java' |
| 6 | Active project session, a skeleton was already created and saved, SceneBuilder not stopped in between | FXML already saved to `/Temp/SceneBuilder/Test.fxml` |  set to `MyCustomController`  |  As the controller skeleton was previously saved to `/somewhere/MyControllerSkeleton.java`, the File Chooser will always propse this name until the SceneBuilder session is restarted. |

Examples:

## Use Case 1 (fresh project, nothing saved, no controller defined)
![Uploading 01_FreshFile_Unsaved.png…]()
