### ISSUE TITLE
FileSystemWatchService is never stopped and is spawned multiple times

### ISSUE THREAD

**Issue by mimmoz81** [gluonhq/scenebuilder#386]
The watchService for user library is never stopped and it is spawned twice or more.
I'm creating this issue as described in #236 
I'm going to do a PR for this shortly (I hope..)

### Expected Behavior
The watchService should be terminated gracefully

### Current Behavior
The watchService is never stopped

### Steps to Reproduce
Import a library from jar/fxml manager.
Drop that library.
Install again.
Drop again.
Install again.

![image](https://user-images.githubusercontent.com/14213760/129048962-b677b22e-2677-4c65-92a6-317d3b0d3ad9.png)

You will have many threads named "FileSystemWatchService" doing the same job and not releasing resources.

![image](https://user-images.githubusercontent.com/14213760/129048693-ba87df15-d96d-46d3-801d-195da04d2b44.png)

**Comment by abhinayagarwal** [comment]
This is a simple change and looks OK to me. I would also like @jperedadnr to have a look a look at it before we go ahead and merge the same.
