### ISSUE TITLE
Update runtime information in About Dialog

### ISSUE THREAD

**Issue by abhinayagarwal** [gluonhq/scenebuilder#413]
Current About Dialog in Scene Builder shows the VM version and name. It should infact show Java version and runtime name.

SB currently uses `${java.vm.version}, ${java.vendor}` to print this information. These should be updated to `${java.version}, ${java.runtime.name}`

### Expected Behavior
Show Java version and runtime name. 

Instead of `17+35-LTS-2724, Oracle Corporation`, it should show `17, OpenJDK Runtime Environment`

### Current Behavior
Shows VM version and name

### Steps to Reproduce
Click on Help Menu -> About

### Your Environment
Ubuntu 20.04

### Screenshots
![sb-about](https://user-images.githubusercontent.com/3197675/134458093-2933bc6e-ddc7-4915-9b52-1806eb905cbf.png)

**Comment by himanshu007-creator** [comment]
Hi @abhinayagarwal , i would like to work on this issue
