### ISSUE TITLE
The filter for excluded custom elements of a jar can't be removed

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#42]
Originally reported by: **Andre Krause (Bitbucket: [akrause](https://bitbucket.org/akrause), GitHub: [akrause](https://github.com/akrause))**

----------------------------------------

So if you import a jar, you can choose if a custom element in this jar should be excluded, so that it doesn't appear in the "Custom" section. 

Therefor, a filter file is written in the Library folder of the SB. But you can't delete custom elements or the complete filter file from within the SB, so the next time you import the same jar and want to include the custom element now, you can't use it in the SB, because it is still excluded. 

There should be an option in the SB to either clear the complete filter, or to remove a custom element from the filter list so that it will be included.

From Saxonia Systems

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/42

**Comment by Oliver-Loeffler** [comment]
With SB16 this does not seem to be an issue anymore. It is possible for each library item to modify the selection if a certain control shall appear in custom controls or not. Also when an artifact is removed from library, the setting can be modified latest when the control is added again.

@abhinayagarwal 
This one also looks as if it can be closed.
