### ISSUE TITLE
Reduce startup times for improved User Experience

### ISSUE THREAD

**Issue by AlmasB** [gluonhq/scenebuilder#442]
Currently the majority of startup time is spent on preparing the first DocumentWindowController (~60% of time) and WelcomeDialogWindow (~40% of time).

The goal is to throw everything we have at getting the WelcomeDialog open as fast we as can for snappy UX, related to #440 

This can be achieved by the following steps:

- [ ] Do not load anything from the file system for WelcomeDialog
- [ ] Pre-bake fxml and CSS into WelcomeDialog code to avoid any parsing
- [ ] Load first DocumentWindowController in the background and only show on demand (that is when the user selects "new" or "open" project)

If the above works as expected, we should be able to get a nice 70-90% boost in startup times.

**Comment by Oliver-Loeffler** [comment]
Very good idea. Did you run benchmarks?

**Comment by AlmasB** [comment]
`System.nanoTime()` between suspected costly calls only to get a rough idea. That's where the above values come from.

**Comment by AlmasB** [comment]
1 and 2 together only provide ~5-10% improvement in speed with quite a lot of drawbacks, since we can't have any resources, meaning no images, no i18n, etc. So trade-off is not good here.

3 ended up being the main bottleneck. This gives ~60% improvement in speed. Please see attached video. On my i9, 6cores, fixed 2.90GHz, startup time improved from 1.9-2.2sec, to 0.7-0.8sec

https://user-images.githubusercontent.com/3594742/149320570-f9ac4325-7896-4567-a771-ae535e62410c.mp4
