### ISSUE TITLE
Development build releases

### ISSUE THREAD

**Issue by AlmasB** [gluonhq/scenebuilder#446]
It would be beneficial for users to be able to access latest development builds and test them immediately after a merge to `master`. I can see some GitHub actions that generate bundles. Could these be duplicated / extended to upload SNAPSHOT bundles to GitHub or other hosting? @abhinayagarwal

**Comment by Oliver-Loeffler** [comment]
How about using the Maven Release plugin, to ensure that we always get correct versions? As of now, the main line is still tagged Scene Builder 17.0.0 (no snapshot version this time).

**Comment by Oliver-Loeffler** [comment]
The Scene Builder releases now work quite well. What I have seen in the issues is, that users like to have a plain app image in a ZIP file and there was also an issue asking for a Snap package. For me this sounds like some work in GH action plus possibly getting JReleaser on board to e.g. build the Snap package.

**Comment by aalmiray** [comment]
FWIW JReleaser can take care of rolling early access releases as well, matter of fact that's how JReleaser is currently setup for publishing it's own rolling releases. Happy to discuss options to setup SceneBuilder.

**Comment by AlmasB** [comment]
thanks @aalmiray 

Essentially, it'd be nice to have something like:

1. a PR is merged to `master`, which triggers a GH action for snapshot release
2. the release artifacts for each OS get uploaded to somewhere on GH

Any support with this or pointers would be great!

**Comment by aalmiray** [comment]
I see. You're looking for something like this if that's the case:

https://github.com/kcctl/kcctl/blob/main/.github/workflows/early-access.yml
https://github.com/jreleaser/jreleaser/blob/main/.github/workflows/early-access.yml

Once a push is made to the default branch (regardless of it's form, could be a direct commit, a PR merge, etc) the workflow will start. You'll need to branch execution into multiple nodes to build platform specific installers via jpackage, the collect all binaries for the final push to the GH release.

Portions of the existing linux|mac|win GH workflows would have to be copied to create the installers (skipping S3 upload of course).

I could help setting up a PR as a starting point.

**Comment by AlmasB** [comment]
There is no rush with this, but if you could provide a draft PR when you have time, that would be a great starting point.

**Comment by aalmiray** [comment]
@AlmasB done. Have a look at #458 whenever you have some time and let me know if any adjustments should be made.
