### ISSUE TITLE
Display "register" window elsewhere in the workflow

### ISSUE THREAD

**Issue by AlmasB** [gluonhq/scenebuilder#448]
### Expected Behavior

Propose to move the register window into "About" menu, or similar, to avoid hindering the user workflow.

### Current Behavior

Currently the register window appears after the WelcomeDialog is hidden at certain intervals

### Context

To maximise user productivity, it is best to avoid any optional blocking / application modal dialogs within the normal workflow.

**Comment by gargoyle** [comment]
I'm happy to have a stab as this one. We need to do anything regarding assigning issues?

**Comment by AlmasB** [comment]
Nice, go for it 👍
