### ISSUE TITLE
Standardise commit messages

### ISSUE THREAD

**Issue by AlmasB** [gluonhq/scenebuilder#451]
In in the long run, it would be beneficial to have a convention for commit messages, so that the changelog over at Releases is generated cleanly.

I propose to add something like this to CONTRIBUTING.md:

## Conventional Commits for Changelogs

The project uses the following commit message guidelines, based on [Conventional Commits 1.0.0](https://www.conventionalcommits.org/en/v1.0.0/):

* **build: message** -- change affects the build system, configuration files, scripts, or external dependencies
* **docs: message** -- change affects documentation **only**
* **feat: message** -- change adds a new or modifies an existing feature
* **fix: message** -- change fixes a bug
* **perf: message** -- change improves performance
* **refactor: message** -- change cleans up or restructures code
* **test: message** -- change that adds new or updates existing tests 
* **repo: message** -- change that is related to repository maintenance

**Comment by Oliver-Loeffler** [comment]
Where would you assign things like header updates to?  `license:` or `header:` ?

**Comment by aalmiray** [comment]
FWIW conventional commits are supported by JReleaser https://jreleaser.org/guide/latest/configuration/release/changelog.html#_conventional_commits

If #458 is accepted and merged it would be trivial to configure CC.

**Comment by Oliver-Loeffler** [comment]
This is a pretty cool feature, didn't know about that. This could ease up the release process a lot.

**Comment by aalmiray** [comment]
More over CC can be checked and enforced. jbangdev/jbang has configuration applied via a bot that can check if commits from a PR follow CC. 

Looping in @maxandersen

**Comment by AlmasB** [comment]
@aalmiray That's great! So if I understand correctly:

When a maintainer manually releases the next version via the GH action from #458, JReleaser can be configured to collate commits since last version and embed into the .md with the release?

**Comment by aalmiray** [comment]
Yes, that is exactly what happens.

**Comment by maxandersen** [comment]
fyi, what I use is https://github.com/apps/semantic-pull-requests

**Comment by abhinayagarwal** [comment]
I am good to go with this proposal and have added sematic-pull-requests app to Scene Builder.
