### ISSUE TITLE
Image property without editor on properties pane

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#46]
Originally reported by: **Luca Domenichini (Bitbucket: [mimmoz81](https://bitbucket.org/mimmoz81), GitHub: [mimmoz81](https://github.com/mimmoz81))**

----------------------------------------

Create a simple custom component that extends from Pane and contains an ImageView inside it.

```
#!java

public class MyImagePane extends Pane {

	private ImageView imageView = new ImageView();
```

Now expose the Image property of the ImageView as
```
#!java

	public ObjectProperty<Image> imageProperty() {
		return imageView.imageProperty();
	}
	public Image getImage() {
		return imageProperty().get();
	}
	public void setImage(Image value) {
		imageProperty().set(value);
	}

```

Expose other properties from ImageView, e.g. fitWidth and fitHeight:

```
#!java

	public DoubleProperty fitHeightProperty() {
		return imageView.fitHeightProperty();
	}
	public double getFitHeight() {
		return fitHeightProperty().get();
	}
	public void setFitHeight(double value) {
		fitHeightProperty().set(value);
	}
	public DoubleProperty fitWidthProperty() {
		return imageView.fitWidthProperty();
	}
	public double getFitWidth() {
		return fitWidthProperty().get();
	}
	public void setFitWidth(double value) {
		fitWidthProperty().set(value);
	}

```

When you use this control on SB, only the 2 fitWidth/fitHeight properties are shown on properties pane. Image property cannot be edited.

![screenshot.1163.png](https://bitbucket.org/repo/L8BBag/images/4055424882-screenshot.1163.png)

Note that extending directly from ImageView instead of embedding it into a Pane, makes the Image property editable...

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/46

**Comment by Oliver-Loeffler** [comment]
Hi @AlmasB, hi @luca-domenichini,

I have tested the provided case with following 2 custom components and think that this issue has already been fixed.
At least its working with Scene Builder 19.

One extending the ImageView:

```java
package custom;

import javafx.scene.image.ImageView;

public class MyExtendingComponent extends ImageView {

}
```

Another one holding an image view with properties exposed:

```java
package custom;

import javafx.beans.property.DoubleProperty;
import javafx.beans.property.ObjectProperty;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.layout.CornerRadii;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;

public class MyComponent extends Pane {
    private ImageView imageView = new ImageView();
    
    public MyComponent() {
        setWidth(250);
        setHeight(250);
        setMinSize(200, 200);
        setBackground(new Background(new BackgroundFill(Color.RED, CornerRadii.EMPTY, getInsets())));
        getChildren().add(imageView);
    }
    
    public ObjectProperty<Image> imageProperty() {
        return imageView.imageProperty();
    }
    public Image getImage() {
        return imageProperty().get();
    }
    public void setImage(Image value) {
        imageProperty().set(value);
    }
    public DoubleProperty fitHeightProperty() {
        return imageView.fitHeightProperty();
    }
    public double getFitHeight() {
        return fitHeightProperty().get();
    }
    public void setFitHeight(double value) {
        fitHeightProperty().set(value);
    }
    public DoubleProperty fitWidthProperty() {
        return imageView.fitWidthProperty();
    }
    public double getFitWidth() {
        return fitWidthProperty().get();
    }
    public void setFitWidth(double value) {
        fitWidthProperty().set(value);
    }
}
```

For both components the available properties, especially the image property, are correctly shown and editable in Scene Builder.

MyComponent:

![CustomComponentProperties](https://user-images.githubusercontent.com/22102800/196815239-c6134ec7-e5f3-4754-935a-3dd6e6f07feb.PNG)

Given that this works now, I think we can close this issue.
What do you thing @AlmasB ?

**Comment by AlmasB** [comment]
Based on the above screenshot, this appears to be working. Thanks.
