### ISSUE TITLE
Error Failed to start Scenebuilder

### ISSUE THREAD

**Issue by semir1121** [gluonhq/scenebuilder#464]
### Expected Behavior
Hey guys i downloaded Scenebuilder and linked the path from intellij to the application but it doesnt work for me. I can open the Application by itself but I cannot open it in Intellij

### Your Environment
IntelliJ

### Screenshots
![image](https://user-images.githubusercontent.com/98037048/150155052-0da79213-d5f1-4151-923c-9eeff5d22b6a.png)

**Comment by Oliver-Loeffler** [comment]
Hi @semir1121,

please try to change the Scene Builder Path in IntelliJ to this one: `C:\Users\<yourusername>\AppData\Local\SceneBuilder\SceneBuilder.exe` 

The reason why this error occurs might be that using the link (`*.lnk` on Windows) together with an FXML file might fail.

**Comment by semir1121** [comment]
> Hi @semir1121,
> 
> please try to change the Scene Builder Path in IntelliJ to this one: `C:\Users\<yourusername>\AppData\Local\SceneBuilder\SceneBuilder.exe`
> 
> The reason why this error occurs might be that using the link (`*.lnk` on Windows) together with an FXML file might fail.

hey oliver,

thank you a lot it worked now

**Comment by Oliver-Loeffler** [comment]
Hi, happy to hear, thus we can close the issue!
