### ISSUE TITLE
Add menu item to show welcome dialog

### ISSUE THREAD

**Issue by AlmasB** [gluonhq/scenebuilder#470]
See https://github.com/gluonhq/scenebuilder/pull/447#issuecomment-1017974430

**Comment by gargoyle** [comment]
I'd be happy to have a stab at this one too if you're happy with my other PR (I think I'm starting to get the hang of it).

**Comment by Oliver-Loeffler** [comment]
Go for it, I'll stay away from this.

**Comment by gargoyle** [comment]
I've opened a draft PR (https://github.com/gluonhq/scenebuilder/pull/490) for the main changes to get the welcome screen to re-display, and generally it works OK with recent files opening new main Scene Builder document windows.

However, I need to figure out how to handle the following issues:-

1. Choosing to open a new empty document seems to do nothing.
2. Choosing any of the other starter templates immediately and without warning replaces the currently open document - even if there are unsaved changes.

**Comment by gargoyle** [comment]
I've resolved the issues above and PR is ready for review.
