### ISSUE TITLE
Provide .editorconfig in project to ensure consistent formatting 

### ISSUE THREAD

**Issue by Oliver-Loeffler** [gluonhq/scenebuilder#485]
Scene Builder code follows a certain formatting style. E.g. spaces are preferred over tabs.
Add a notice either to README.md or to CONTRIBUTING.md, that Netbeans, Eclipse and VSCode require a plugin and IntelliJ does not. Add a link to https://editorconfig.org/.

### Expected Behavior
When Scene Builder project is opened in IDE, code formatting rules and styles are imported from .editorconfig.
Let Maven run the required checks (additionally to check style) [editorconfig-maven-plugin](https://ec4j.github.io/editorconfig-maven-plugin/). 

Setup to start with setup:
* no tabs, just spaces, 4 spaces indent, default line break to `\n` for `*.java`, `*.css` and `*.properties`
* add or complement README.md or CONTRIBUTING.md with a section on how to properly setup development environment

### Current Behavior
When Scene Builder project is opened in IDE, existing formatting conventions in IDE may break existing format in files.

### Context
Code formatting and use of spaces/tabs is a recurring issue in PRs and is time consuming and annoying for contributors and reviewers.

**Comment by abhinayagarwal** [comment]
@Oliver-Loeffler does `editorconfig-maven-plugin` automatically overwrite files to make the necessary changes?

**Comment by Oliver-Loeffler** [comment]
@abhinayagarwal Yes, indeed it does, this is the beauty of this tool.

In order to format the code, one needs to run:

```
mvn editorconfig:format
```

Its described here: https://ec4j.github.io/editorconfig-maven-plugin/
