### ISSUE TITLE
Add a copy function for ColorPicker

### ISSUE THREAD

**Issue by leewyatt** [gluonhq/scenebuilder#497]
I made a short video presentation:   https://youtu.be/_rfFx7NeQQE
After the color picker selects the color, click the copy button can copy the Java code or CSS code of the color

### Expected Behavior

After the color picker selects the color, click the copy button, and we can get the CSS code or Java code of the current color;

### Current Behavior

For example, gradient can only generate corresponding fxml code We can't generate the Java code or CSS code .

### Context

    Many times, we need color's java code or CSS code; For example, make cool gradient animation with color; 
    Or we need to modify the color of control through CSS;
    It is troublesome to write the color code manually, especially the gradient color;
    I have developed an idea plug-in with about 1000 downloads per month,
    Because IDEA supports swing development plug-ins, its support for JavaFX is not good enough, So I want to migrate the function of copying color codes to scenebuilder,
my idea plugin:   https://plugins.jetbrains.com/plugin/17514-javafx-tools
    In the future, I plan to add other very useful functions to scenebuilder.

**Comment by abhinayagarwal** [comment]
I watched the video. This seems to be a very useful feature 👍

**Comment by leewyatt** [comment]
Thank you, ColorPicker/PaintPcker of SceneBuilder is already very powerful, we should make full use of it;
