### ISSUE TITLE
Workflow failing with rolling releases

### ISSUE THREAD

**Issue by abhinayagarwal** [gluonhq/scenebuilder#499]
With recent merge of PR https://github.com/gluonhq/scenebuilder/pull/458 , the workflows are failing.

**Comment by AlmasB** [comment]
After #498 the failures seem to be on Windows and Mac, related to signing packages. Linux seems fine.

https://github.com/gluonhq/scenebuilder/actions/runs/1752375800

**Comment by abhinayagarwal** [comment]
I will have a look at signing tomorrow. Thanks for the quick fix on the workflows @aalmiray .

**Comment by aalmiray** [comment]
I wonder if it has something do with using all caps for the secret names passed to the reusable workflows.
I've got another reusable workflow working but the secrets are lowercase + kebab case.

**Comment by aalmiray** [comment]
It's live!
https://github.com/gluonhq/scenebuilder/actions/runs/1756336012

https://github.com/gluonhq/scenebuilder/releases/tag/early-access

**Comment by AlmasB** [comment]
@abhinayagarwal windows signing started to fail again, please can you check when around
