### ISSUE TITLE
Zoom to 400% Shows Inverted Picture of Scene Builder Controls

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#51]
Originally reported by: **Carl Walker (Bitbucket: [walkerca](https://bitbucket.org/walkerca), GitHub: [walkerca](https://github.com/walkerca))**

----------------------------------------

Selecting Zoom to 400% pauses the tool for about 1 minute (on a fast computer) and then produces the view of the attached screenshot.  Zoom to other percentages works fine.

This is Scene Builder 8.0.0 running Java 1.8.0_40b25 on Ubuntu 15.10.

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/51

**Comment by Oliver-Loeffler** [comment]
This seems to be no issue anymore. The problem occurs at zooms way beyond 1000%.
I've tested this with SB19 on WIn10, macOS 12.0.1 and Fedora 36.

@AlmasB This one can be closed possibly - does not seem to be an issue anymore.
