### ISSUE TITLE
SceneBuilder Preferences

### ISSUE THREAD

**Issue by cbm64chris** [gluonhq/scenebuilder#511]
I want to recent everything about SceneBuilder and begin from scratch to validate if an issue exists in reference the fx:include FXML property on macOS.

* Deleted /Application/SceneBuilder.app
* Deleted ~/.scenebuilder
* Deleted ~/Library/Preferences/com.oracle.javafx.plist
* Deleted ~/Library/Preferences/com.gluonhq.scenebuilder.plist
* Deleted ~/Library/Application\ Support\Scene\ Builder

The recent files are still there when a newly installed version in run from dmg.

I have event rebooted after removing the files to release any remaining handles. But the recent files persists as do other settings.

MacBook Air (M1, 2020)
macOS 12.2
JDK 17.0.2

Thoughts?

**Comment by cbm64chris** [comment]
Ok, sorry....inevitably it cleared the history straight after I posted this! Typical!

**Comment by Oliver-Loeffler** [comment]
It is now possible to clear recent files via: file menu / open recent / clear menu command.
