### ISSUE TITLE
Error Custom StyleableProperty In SceneBuilder

### ISSUE THREAD

**Issue by HiouaniHalim** [gluonhq/scenebuilder#532]
### Screenshots

Welcome
I encountered a problem while creating a custom property in scene builder where I can't get this property, so please give me a solution to this problem as soon as possible if possible
You can watch this picture in order to understand what I want to say
Currently this property
![bandicam 2022-03-26 18-48-18-613](https://user-images.githubusercontent.com/37694759/160251774-b27b3c5d-fc3b-4637-bc79-793dbd25cbda.jpg)

![Uploading bandicam 2022-03-26 18-49-08-461.jpg…]()

![bandicam 2022-03-26 18-48-18-613](https://user-images.githubusercontent.com/37694759/160251768-7e073afc-64a5-45de-ac81-c8b34da2016e.jpg)

And here this property does not appear in scene builder
![bandicam 2022-03-26 18-50-07-685](https://user-images.githubusercontent.com/37694759/160251814-b111683d-eff8-487b-8b06-586f10a8b602.jpg)

I wanna get like this in scene builder
![bandicam 2022-03-26 19-04-53-566](https://user-images.githubusercontent.com/37694759/160251844-bbfaffa2-60e1-466c-b42c-0c9d9fde3ccb.jpg)

**Comment by HiouaniHalim** [comment]
@aalmiray Can you help me please for this problem ?

**Comment by aalmiray** [comment]
@HiouaniHalim I'll advise you to ask @abhinayagarwal or @AlmasB as they take care of this project, not me.

**Comment by HiouaniHalim** [comment]
@abhinayagarwal thanks

**Comment by Oliver-Loeffler** [comment]
Hi @AlmasB, could you please assign this one also to me?

**Comment by Oliver-Loeffler** [comment]
Hi @HiouaniHalim , I found a solution for this. There will be a PR soon which will enable use of the already available Insets editor with custom defined insets. It took me a while to figure out how this works. It is now about writing a test case and preparing the PR. `My Insets` and `My Paint` are properties of a custom control.

<img width="658" alt="SceneBuilder_CustomControl_InsetsProperty" src="https://user-images.githubusercontent.com/22102800/197295882-928dfa27-8d02-4957-b2e1-2c53ddb01f44.png">

**Comment by Oliver-Loeffler** [comment]
Hi @HiouaniHalim,
please try out the leading-edge branch of Scene Builder at https://github.com/Oliver-Loeffler/scenebuilder.git.
This one already allows editing of Insets - beware, its not the official one yet - but good for testing.

**Comment by HiouaniHalim** [comment]
> ```java
> import javafx.beans.property.ObjectProperty;
> import javafx.beans.property.SimpleObjectProperty;
> import javafx.geometry.Insets;
> import javafx.scene.control.Label;
> import javafx.scene.layout.Background;
> import javafx.scene.layout.BackgroundFill;
> import javafx.scene.layout.Border;
> import javafx.scene.layout.BorderStroke;
> import javafx.scene.layout.BorderStrokeStyle;
> import javafx.scene.layout.BorderWidths;
> import javafx.scene.layout.CornerRadii;
> import javafx.scene.layout.StackPane;
> import javafx.scene.paint.Color;
> import javafx.scene.text.Font;
> import javafx.scene.text.FontWeight;
> 
> public class CustomNodeWithInsets extends StackPane {
> 
>     private final StackPane innerPane;
>     
>     private final StackPane centerPane;
>     
>     public CustomNodeWithInsets() {
>         setBackground(new Background(new BackgroundFill(Color.BLACK, CornerRadii.EMPTY, Insets.EMPTY)));
>         setBorder(new Border(new BorderStroke(Color.WHITE, BorderStrokeStyle.SOLID, CornerRadii.EMPTY, new BorderWidths(2))));
>         innerPane = new StackPane();
>         innerPane.setBackground(new Background(new BackgroundFill(Color.ORANGE, new CornerRadii(10), Insets.EMPTY)));
>         innerPane.setBorder(new Border(new BorderStroke(Color.WHITE, BorderStrokeStyle.SOLID, new CornerRadii(10), new BorderWidths(2))));
>         innerPane.setMinSize(100, 100);
>         innerPane.setMaxSize(590, 590);
>         innerPane.setPrefSize(590, 380);
>         innerPane.paddingProperty().bind(innerFrameProperty());
> 
>         centerPane = new StackPane();
>         centerPane.setBackground(new Background(new BackgroundFill(Color.BLUEVIOLET, new CornerRadii(10), Insets.EMPTY)));
>         centerPane.setBorder(new Border(new BorderStroke(Color.WHITE, BorderStrokeStyle.SOLID, new CornerRadii(10), new BorderWidths(2))));
>         centerPane.setMinSize(100, 100);
>         centerPane.setMaxSize(580, 570);
>         centerPane.setPrefSize(580, 360);
> 
>         Label label = new Label("Custom Control Insets Demo");
>         label.setBorder(new Border(new BorderStroke(Color.BLACK, BorderStrokeStyle.SOLID, new CornerRadii(8), new BorderWidths(4))));
>         label.paddingProperty().bind(textPaddingProperty());
>         label.setBackground(new Background(new BackgroundFill(Color.WHITE, new CornerRadii(10), Insets.EMPTY)));
>         label.setFont(Font.font(label.getFont().getFamily(), FontWeight.BLACK, 14));
>         centerPane.getChildren().add(label);
>         innerPane.getChildren().add(centerPane);
> 
>         getChildren().add(innerPane);
>         setMinSize(100, 100);
>         setMaxSize(600, 600);
>         setPrefSize(598, 396);
>         setWidth(600);
>         setHeight(400);
> 
>         paddingProperty().bind(outerFrameProperty());
>     }
> 
>     private ObjectProperty<Insets> outerFrame;
> 
>     public void setOuterFrame(Insets value) {
>         this.outerFrameProperty().setValue(value);
>     }
> 
>     public Insets getOuterFrame() {
>         return this.outerFrame == null ? new Insets(90, 40, 30, 160) : outerFrameProperty().getValue();
>     }
> 
>     public ObjectProperty<Insets> outerFrameProperty() {
>         if (this.outerFrame != null) {
>             return this.outerFrame;
>         }
>         this.outerFrame = new SimpleObjectProperty<>(new Insets(90, 40, 30, 160));
>         return this.outerFrame;
>     };
> 
>     private ObjectProperty<Insets> innerFrame;
> 
>     public void setInnerFrame(Insets value) {
>         this.innerFrameProperty().setValue(value);
>     }
> 
>     public Insets getInnerFrame() {
>         return this.innerFrame == null ? new Insets(20) : innerFrameProperty().getValue();
>     }
> 
>     public ObjectProperty<Insets> innerFrameProperty() {
>         if (this.innerFrame != null) {
>             return this.innerFrame;
>         }
> 
>         this.innerFrame = new SimpleObjectProperty<>(new Insets(20));
>         return this.innerFrame;
>     };
>     
>     private ObjectProperty<Insets> textPadding;
> 
>     public void setTextPadding(Insets value) {
>         this.textPaddingProperty().setValue(value);
>     }
> 
>     public Insets getTextPadding() {
>         return this.textPadding == null ? new Insets(15, 40, 15, 40) : textPaddingProperty().getValue();
>     }
> 
>     public ObjectProperty<Insets> textPaddingProperty() {
>         if (this.textPadding != null) {
>             return this.textPadding;
>         }
>         this.textPadding = new SimpleObjectProperty<>(new Insets(15, 40, 15, 40));
>         return this.textPadding;
>     };
> }
> ```

not work see that:

**Comment by HiouaniHalim** [comment]
@Oliver-Loeffler the example not work see that :
![error](https://user-images.githubusercontent.com/37694759/198269996-6e661845-44a0-4eb4-b7ee-649a5105f729.PNG)

**Comment by Oliver-Loeffler** [comment]
H @HiouaniHalim,

please re-open the issue, I will continue working on that.
Thanks!

**Comment by Oliver-Loeffler** [comment]
On Windows, the following steps are needed to get it working (having Java and Maven installed):
The important thing is to clone the "leading-edge" branch and to run "mvn install" with it.

```cmd
git clone --branch leading-edge git@github.com:Oliver-Loeffler/scenebuilder.git
cd scenebuilder
mvn install
mvn javafx:run -f app
```

Go SceneBuilder library manager and add `app\target\classes` location as root folder with class files.
There should be a class file `custom.CustomNodeWithInsets.class`. 

If this fails again, I'll publish an MSI file. The custom control example class is now part of the branch.

**Comment by HiouaniHalim** [comment]
@Oliver-Loeffler am using scene builder.msi version 19.0.0

**Comment by abhinayagarwal** [comment]
Hi @HiouaniHalim ,

Did you get a chance to review PR https://github.com/gluonhq/scenebuilder/pull/594 ?

**Comment by Oliver-Loeffler** [comment]
@HiouaniHalim,
this Scene Builder release will allow to test this.
https://www.jdeploy.com/~scenebuilder-leading-edge

**Comment by Oliver-Loeffler** [comment]
For testing, there is a sample control with 3 layers of insets. After the project is built, it is available in `scenebuilder\app\target\classes` directory. One can add this directory to Scenebuilder to import control from using the JAR/FXML Manager aka. Library Manager. The following video shows how the inset editor works and how it is enabled for the custom control.

https://user-images.githubusercontent.com/22102800/227802576-49b0fae2-d27f-4737-812f-a8a83e030a82.mp4

**Comment by Oliver-Loeffler** [comment]
I've updated the insets editing PR as the demo class was missing.

**Comment by HiouaniHalim** [comment]
Im using scene builder 2019.msi and I have same problem for that problem
I hope there is an update for the problem in the urgent team, thanks

**Comment by Oliver-Loeffler** [comment]
As of now this only works with Scenebuilder LE where the PR is already integrated. 

https://www.jdeploy.com/~scenebuilder-leading-edge

The source code of LE is available at:
https://github.com/Oliver-Loeffler/scenebuilder

The related PR has not yet been merged into Scene Builder main line.

**Comment by HiouaniHalim** [comment]
Ok, thanks for the update.

**Comment by HiouaniHalim** [comment]
hi, I find error in scene builder LE please  see pic below

![c1](https://github.com/gluonhq/scenebuilder/assets/37694759/89e18bfc-759e-4d7b-a5ed-51f0efb98013)
and this 
![c2](https://github.com/gluonhq/scenebuilder/assets/37694759/4d73177d-09f5-4ce1-885a-a469c4f4e399)

properties and layout  not working
