### ISSUE TITLE
build: workflow to build Scene Builder for M1

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/scenebuilder#552]
Given that GitHub doesn't currently have runners for macOS AArch64, it is possible to use a self-hosted runner, installed on an M1, to build Scene Builder from the usual workflow, in order to have early access versions or releases.

In this case, it should just be a matter of adding the necessary changes in the workflow to include a new platform.

The only concern is the availability of the self-hosted runner (which it's not expected to be online 24/7).

**Comment by AlmasB** [comment]
If it is not expected to be online 24/7, perhaps we could have a manually triggered workflow (like `release.yml`) for this. There is no need for us to produce EA builds for M1 for every commit, only for selected major changes.

**Comment by aalmiray** [comment]
Additional settings in `pom.xml` would be needed to handle the extra artifact with JReleaser. This should be done with a profile to override the "default" behavior.

**Comment by jperedadnr** [comment]
@erwin1 could we add the self hosted runner so we can also build for M1?
