### ISSUE TITLE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project kit: Fatal error compiling: error: release version 17 not supported -> [Help 1] Arm64v8

### ISSUE THREAD

**Issue by pedrombmachado** [gluonhq/scenebuilder#607]
Fails to compile maven-compile-plugin because of the version of the compiler (i.e. 17).

### Expected Behavior
Compilation finishes without error. 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project kit: Fatal error compiling: error: release version 17 not supported -> [Help 1]

### Current Behavior
Compilation breaks with the message related to the compiler version (i.e. 17)

### Steps to Reproduce
Pick the armv8 architecure from https://hub.docker.com/repository/docker/pedrombmachado/ntu_lubuntu and run
'''
$ docker run -it --rm -p "3390:3389/tcp"  pedrombmachado/ntu_lubuntu:arm64v8_latest
'''
Install default-jre and maven by running
'''
$ sudo apt update && sudo apt upgrade -y && sudo apt install default-jre maven -y
'''
clone the SceneBuilder repo and buil.

### Your Environment
Ubuntu 20.04 arm 64v8
java version - openjdk 11.0.17
maven - Apache Maven 3.6.3

**Comment by Oliver-Loeffler** [comment]
Hi, is there no Java-17 for the target platform? When switching to Java-17 the build will work.

**Comment by Oliver-Loeffler** [comment]
I see that our readme is wrong, as it still states Java 11 where it should be Java 17 instead.

**Comment by pedrombmachado** [comment]
Thank you @Oliver-Loeffler solved the problem by installing the correct version of maven using the SDKMan
