### ISSUE TITLE
Navigating controls hierarchy up

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#62]
Originally reported by: **Luca Domenichini (Bitbucket: [mimmoz81](https://bitbucket.org/mimmoz81), GitHub: [mimmoz81](https://github.com/mimmoz81))**

----------------------------------------

When selection is on a control (both in hierarchy pane or in designer) it would be useful to have to ESC key to focus the parent control in hierarchy.
This way SB is near to how others wysiwyg editors do when pressing ESC key..

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/62

**Comment by AlmasB** [comment]
This is a duplicate of #388 hence this instance is closed.
