### ISSUE TITLE
build: Add OperatorWrap rule to checkstyle

### ISSUE THREAD

**Issue by Oliver-Loeffler** [gluonhq/scenebuilder#620]
As learned with issue-73, operators are supposed to be wrapped into spaces.
Nicely Checkstyle has a rule for that.

### Expected Behavior
Unwrapped operators such as in `content=textArea.getText();` should be detected by Checkstyle.
Checkstyle should issue a warning for such cases. Ideally the source looks like: `content = textArea.getText();`.

### Current Behavior
Checkstyle does not detect those, as it does not check for this pattern.

### Context
Inconvenience / extra effort in Pull Request reviews. Would be good if we could avoid this by using Checkstyle.

I'll open a PR with a modified `checkstyle.xml`.
If there other rules we should implement, we can do this in the related PR.

**Comment by Oliver-Loeffler** [comment]
Actually I was wrong with this one. Just played around with Checkstyle and found that OperatorWrap only ensures that we get the following pattern when line wraps are needed:

Checkstyle will complain this one:

```java
        int d = c +
                10;
```

It will permit:

```java
        int d = c
                + 10;
```

Nevertheless, this rule is okay to have. What I actually wanted (I am sorry, did not check carefully enough) is the following:

```xml
        <module name="WhitespaceAfter"/>
        <module name="WhitespaceAround"/>
```

This setup ensures that we actually get the whitespaces around lambdas, around operators `+`, `||`, etc.
Interestingly this also ensures that we have actually no whitespace before comma but a following whitespace after the comma.
I'll test my PRs using those settings and rework them accordingly.

If you agree @abhinayagarwal, I'll issue an updated PR referring this issue.

**Comment by abhinayagarwal** [comment]
My preference would be for all java sources to have these checkstyles.

**Comment by Oliver-Loeffler** [comment]
I will see to geht this working for the tests as well.
