### ISSUE TITLE
Give a way to chang the version of FXML file

### ISSUE THREAD

**Issue by Syrea7** [gluonhq/scenebuilder#640]
When I finished my fxml on scenebuilder.
I use "Ctrl+S".
xmlns="http://javafx.com/javafx/21.0.0"

How can I change "21.0.0"  to "17" by set up instead of edit the fxml file.
I hope it is a auto function when I save it.
I don't want to edit fxml every time.
My JDK is 17 and scenebuilder is 21.

**Comment by Oliver-Loeffler** [comment]
Hi @AlphaSyrea, 

as of now, there is no built in way to change the version number in the FXML header using the GUI.
The only way is to use Scene Builder 17, which does this. Each Scene Buuilder version uses a distinct OpenJFX version, which is written into the FXML. Thanks for raising the issue, its a very good and valid point!

Currently, the version number causes only a warning to appear.
Question to @abhinayagarwal, is there any way to suppress this version warning?

As of now, I would not expect any trouble by using Scene Builder 20 created FXMLs with JavaFX 17. The generated FXMLs will be fine and are supposed to be compatible.

**Comment by bernardoamorim7** [comment]
@AlphaSyrea You can add `java-options=-Djavafx.version=null` or `java-options=-Djavafx.version=17` to your SceneBuilder.cfg under [JavaOptions]. Should fix the issue for you.
