### ISSUE TITLE
No log file created on Windows/Linux

### ISSUE THREAD

**Issue by credmond** [gluonhq/scenebuilder#641]
### Expected Behavior
Log file to be created in log directory reported in About dialog (Windows/Linux).

### Current Behavior
No log file.

### Steps to Reproduce
Run app, go to log folder, observe no log file.

### Your Environment

Build Information
Version 20.0.0
Date: 2023-05-08 14:08:52
JavaFX Version: 20.0.1
Java Version: 20, OpenJDK Runtime Environment

Logging
The default configuration stores logging output in a file named scenebuilder-20.0.0.log (possibly followed by a trailing '.' and a digit).
The default file path is C:\Users\zzz\.scenebuilder\logs\scenebuilder-20.0.0.log

JavaFX
20.0.1

Java
20.0.1, OpenJDK Runtime Environment

### Screenshots
N/A

**Comment by credmond** [comment]
Updated as also observed in Linux.

Given how buggy, brittle, and problematic this software is, I think it's important to at least have a working logger.

**Comment by credmond** [comment]
Gluon: can someone address this? SceneBuilder does not log to a log file, despite saying it does in the about dialog.

**Comment by credmond** [comment]
I have fixed this here: https://github.com/gluonhq/scenebuilder/pull/658 

It has been a bug since 2021.

**Comment by Oliver-Loeffler** [comment]
Closed with #658.
SceneBuilder now writes logs into the desired location.
