### ISSUE TITLE
Opening the OS-supplied File Manager (other than Nautilus) fail

### ISSUE THREAD

**Issue by tudogeorge** [gluonhq/scenebuilder#674]
Commands that require launching the OS File Manager fail with the following exception:
`java.io.IOException: Cannot run program "nautilus": error=2, No such file or directory`.

I tried
 - File > Reveal on Desktop
 - File > Include > Reveal <fileName> in Explorer

### Expected Behavior
The OS-supplied File Manager application should open at that file's location and with that file selected.

### Current Behavior
The following exception is thrown: `java.io.IOException: Cannot run program "nautilus": error=2, No such file or directory`.
The error message popping up at "Reveal <fileName> in Explorer" is misleading (it says "File <fullFilePath> cannot be found" instead of "Could not reveal <fileName> / <filePath>".

### Steps to Reproduce
- On a Linux distribution with a file manager other than Nautilus, open the Scene Builder application
- Create and save an FXML file (CHILD_FILE.FXML) - **do not close Scene Builder**
- _Reproduce the issue on "Reveal on Desktop"_ by accessing File > Reveal on Desktop
- Create and save another FXML file (PARENT_FILE.FXML) - this instance can be closed
- Include CHILD_FILE.FXML into PARENT_FILE.FXML
- In the left-hand side of the editor, in the Document > Hierarchy section, select the included file
- _Reproduce the issue on "Reveal <fileName> in Explorer"_ by accessing File > Include > Edit 'CHILD_FILE.FXML' in Explorer

### Environment
OS: Kubuntu 22.04; file manager: Dolphin 21.12.3

Scene Builder Product Version
JavaFX Scene Builder 21.0.0

Build Information
Version 21.0.0
Date: 2023-10-05 12:11:04
JavaFX Version: 21
Java Version: 21, OpenJDK Runtime Environment

**Comment by Oliver-Loeffler** [comment]
Besides making the file browser configurable, we could try following approach for Linux:

* check if `nautilus` exists (e.g. using `which nautilus`) and then prefer the first occurance of it
* check if `dolphin` exists (on Kubuntu) and then prefer the first occurance of it

If neither `nautilus` or `dolphin` are found, we could try to find `xdg-open`. If that exists, we could run `xdg-open /directory`.

That would at least solve this particular issue on Kubuntu.

**Comment by Oliver-Loeffler** [comment]
## Experiment
I've just collected how the error messages look like for the case an exception is raised.

* 1:  File / Reveal in Explorer - (`DocumentWindowController.performRevealAction()`)
![grafik](https://github.com/user-attachments/assets/6427d21d-183a-43a2-8f1f-d3ca2ba7141c)

![grafik](https://github.com/user-attachments/assets/bf58cd68-f8a1-48b0-a02d-98f4623238a8)

* 2: File / Include / Reveal <xyz.fxml> in Explorer - (`EditorController.performRevealIncludedFile()`)

![grafik](https://github.com/user-attachments/assets/d9e52b5f-a18e-446d-a116-975960c3f484)

![grafik](https://github.com/user-attachments/assets/6e2aad9f-7418-4ea7-9d1f-83da5eb63893)

If a file was properly included, it cannot be missing at all.

There is a 3rd occasion for this pattern in `ResourceController.performRevealResource()`. Same thing here (it uses `EditorPlatform.revealInFileBrowser())`.

Conclusion:

## Bad things:

* Both dialogs lack the application icon.
* Despite the same error caused the problem, both dialogs show a different explanation whereas the message in case 2 is mislieading.
* Besides dialogs, the exit code of the process launched is not evaluated. An exit code `!=0` can be assumed as an indication of an error without a related exception. Hence its useful to catch the exit code and to evaluate it accordingly.

## Good things:

* The errors are catched and handled.
* The stacktrace is provided to the details view.

## Aproach:

* The user must be able to figure out, what went wrong. Hence the relevant details must be passed into the log.
* The system call might fail for various reasons. One is, the actual program to be launched is missing. Another one is that the program is launched the wrong way. Or the directory to be revealed is missing.
