### ISSUE TITLE
Update build to use Java and JavaFX 22

### ISSUE THREAD

**Issue by Oliver-Loeffler** [gluonhq/scenebuilder#685]
With the release of OpenJFX 22 we can update from JavaFX 21.0.1 to JavaFX 22

### Expected Behavior
SceneBuilder uses OpenJFX 22

### Current Behavior
SceneBuilder uses OpenJFX 21.01

### Context
SceneBuilder, as one demonstrator of JavaFX capabilities, usually uses the latest available version of OpenJFX.

**Comment by abhinayagarwal** [comment]
I have updated the title of the issue. We should use it to bump both Java and JavaFX versions.
