### ISSUE TITLE
Which is the best documentation for learning JavaFX?

### ISSUE THREAD

**Issue by MubarakNative** [gluonhq/scenebuilder#695]
I'm Mubarak Basha, also known as "Mubarak Native," a Native Android developer. While exploring JavaFX and its features, I encountered challenges when implementing more complex tasks like Canvas and Custom Components. Unfortunately, I found that existing technical documentation only covers the basics. Here are the sources I've explored:

[dev.java](https://dev.java/learn/javafx/): Covers only the fundamentals.
[openjfx.io](https://openjfx.io/openjfx-docs/#next-steps) or [openjfx.io](https://openjfx.io/javadoc/21/): Provides new API references, but lacks in-depth tutorials.
[docs.oracle.com/javafx/2/](https://docs.oracle.com/javafx/2/): Outdated documentation.
Despite these official sources, I also searched through community-driven documentation like [fxdocs](https://fxdocs.github.io/docs/html5/#_introduction). Are there any other advanced-use-case documents you can recommend?

**Comment by Oliver-Loeffler** [comment]
Hi, there are some more nice JavaFX tutorials available. A short list is for example:

* https://jenkov.com/tutorials/javafx/index.html
* https://www.baeldung.com/javafx
* https://codestory.de/10623/anleitung-zum-javafx-fuer-anfaenger
* https://code.makery.ch/library/javafx-tutorial/part1/

There are also quite nice video tutorials available.

* https://www.youtube.com/@AlmasB0/videos
* https://www.youtube.com/@FrankDelporte

Those I can recommend.

**Comment by MubarakNative** [comment]
Ah, i see that thanks for your research effort although there are pretty good docs available But i think javafx community is relatively low compared to electron.js.
