### ISSUE TITLE
Java language level for Scene Builder Kit

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/scenebuilder#721]
Kit and App are built with same Java level as JavaFX release (currently 23).
While this is not an issue for App, which is distributed with its own JRE, if other third party projects want to use Kit, they are forced to set up the same level, and this shouldn't be the case: Kit should be built with the lower level possible (currently 21) 

### Expected Behavior

Kit should work for any Java 21+ project.

### Current Behavior
Adding Kit to a project running with Java level 21 gives:
```
[ERROR] [4,38] module not found: com.gluonhq.scenebuilder.kit
```

**Comment by johanvos** [comment]
I agree that standardizing on Java 21 is a good balance.
