### ISSUE TITLE
Copy Skeleton by CMD+C on Mac copys FXML into Clipboard

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#73]
Originally reported by: **Alexander Casall (Bitbucket: [acasall](https://bitbucket.org/acasall), GitHub: Unknown)**

----------------------------------------

Copy Skeleton by CMD+C on Mac copys FXML into Clipboard

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/73

**Comment by Oliver-Loeffler** [comment]
@sialcasa This will eventually be solved. The way how KeyCodes are read and events are collected seems kind of tricky.
