### ISSUE TITLE
feat: Some I18N properties have no existing translation (Locales: zh_CN, ja)

### ISSUE THREAD

**Issue by Oliver-Loeffler** [gluonhq/scenebuilder#734]
Scene Builder allows user interface internationalization.
As of now English (default), Chinese (zh_CN) and Japanese (ja) translations do exist.

### Expected Behavior
* Existing zh_CN and ja translations match default english properties

### Current Behavior
* Some properties which exist in default language files are not available in zh_CN and ja language files

### Context
* Proper internationalization leads to a more consistent user experience.

**Comment by ktgw0316** [comment]
@Oliver-Loeffler OK, I'll update the Japanese translation after #711 is merged.

**Comment by Oliver-Loeffler** [comment]
Hi @ktgw0316, thanks for your support, thats great News.
