### ISSUE TITLE
Wrong macOS package for Intel Macs

### ISSUE THREAD

**Issue by Aektann78** [gluonhq/scenebuilder#735]
Installing package for Intel Mac on versions 23-24 contains the image built for Arm-based Mac.
### Expected Behavior
On opening the Intel Mac dmg the application should be runnable on Intel-based build of macOS
### Current Behavior
Currently the package built for Intel-based Mac gets the error on launch, telling that this app cannot be used on this Mac.

### Steps to Reproduce
Mount the dmg for Intel Mac, try to launch the application from inside or copy it anywhere and try ro launch. You'll get the error telling that this app cannot be used on this Mac.

### Your Environment
Intel-based MacBook Pro 15' 2018, macOS 15.

**Comment by jperedadnr** [comment]
The issue is due to the macOS-latest runner used in the workflow 
https://github.com/gluonhq/scenebuilder/blob/master/.github/workflows/bundles-mac.yml#L39

It should be macos-13

**Comment by trashgod** [comment]
For reference, this issue is referenced [here](https://stackoverflow.com/q/79060237/230513).
