### ISSUE TITLE
Early access release includes non-artifact files

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/scenebuilder#768]
After #766, the early access workflow publishes, as GitHub early access release, txt and arc files along with the binaries of the artifacts.
Those shouldn't be there.

**Comment by aalmiray** [comment]
Those files are used to allow consumers perform verifications on published artifacts. Why would you want to skip them from a release?

**Comment by jperedadnr** [comment]
Note this is only for the GitHub release block (not for Maven Central). Having the signatures/checksums with the binaries makes it confusing for users that simply want to download from the GitHub release. 

So far, we didn't publish them, as they only show up now after we started signing them for the Scene Builder Kit release to Maven Central.

**Comment by aalmiray** [comment]
Is it really confusing for users? I mean, a txt file that does not match the name of the intended artifact (the kit) plus another filename with `.asc` extension. Alas, it's your prerogative as project maintainer. The good thing is if those files were to be requested by users then enabling is just a quick DSL update away ;-)
