### ISSUE TITLE
WARNING: CSS Error parsing in-line style '-fx-background-image: ;': Unexpected token ';' at [1,22]

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/scenebuilder#774]
Adding a style class in the Inspector->Style textField, throws a warning before waiting until the value to such style class is set:
```
Oct 23, 2024 5:43:28 PM javafx.css.CssParser term
WARNING: CSS Error parsing in-line style '-fx-background-image: ;' from com.oracle.javafx.scenebuilder.kit.editor.panel.inspector.editors.StyleEditor$StyleableStub@4fa47aa3: Unexpected token ';' at [1,22]
```

### Expected Behavior

No warning is thrown if the value field is empty

### Current Behavior

A warning is thrown when value field is empty

### Steps to Reproduce

Open Scene Builder, empty template, add an anchor pane, go to Inspector -> Properties -> Style, when context menu shows up, select `-fx-background-color` for instance. The context menu gets closed and the warning is printed out, as there is no value set yet.

**Comment by abhinayagarwal** [comment]
Unable to reproduce on `master` branch using the "Steps to Reproduce" from the description.

**Comment by jperedadnr** [comment]
See logs or add a ConsoleHandler to logging.properties
