### ISSUE TITLE
Scene Builder 8.2.0 unexpectedly quits when looking for a repository

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#82]
Originally reported by: **Fernando Carvajal (Bitbucket: [ferchop1089](https://bitbucket.org/ferchop1089), GitHub: [ferchop1089](https://github.com/ferchop1089))**

----------------------------------------

When I try to find a repository or add one manually the application terminates abruptly.
I've run from command line and shows the following:

```
#!command line

user@user-A45VD:~$ /opt/SceneBuilder/./SceneBuilder
jun 18, 2016 11:15:25 AM com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher exploreAndUpdateLibrary
INFORMACIÓN: Start exploring JAR /home/fernando/.scenebuilder/Library/controlsfx-8.40.10.jar
jun 18, 2016 11:15:27 AM com.oracle.javafx.scenebuilder.app.SceneBuilderApp logTimestamp
INFORMACIÓN: JavaFX Scene Builder started
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
*** Error in `/opt/SceneBuilder/./SceneBuilder': double free or corruption (out): 0x00007f4cd00ae4a0 ***
Abortado
```
* S.O: Debian 8 KDE - 64 bits
* java version "1.8.0_91"

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/82

**Comment by abhinayagarwal** [comment]
This is no longer reproducible in latest SB
