### ISSUE TITLE
Gridpane Bug

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#9]
Originally reported by: **Alexander Casall (Bitbucket: [acasall](https://bitbucket.org/acasall), GitHub: Unknown)**

----------------------------------------

### 1.Start with this FXML ###

```
#!fxml

<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.scene.layout.GridPane?>

<GridPane xmlns:fx="http://javafx.com/fxml/1">
    <!-- TODO Add Nodes -->
</GridPane>

```

### 3. Drag an Control to the Screen ###
![Add Control](http://s15.postimg.org/yn6gbknp7/Add_Control_To_Grid.png)

### 4. Add second Control by D&D the element on the right boarder of the Grid  
--> The expected behavior is a new column 
--> What happens: Nothing
![Add second control](http://s13.postimg.org/nefvar6w7/Add_second_Control_To_Grid.png)

### How to Workaround ###

--> Close Scene Builder and Reopen the File, then you can do Step 4 and a new column is added

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/9

**Comment by Oliver-Loeffler** [comment]
This is not reproducible anymore with SB16.
Adding a component to the FXML worked fine, also adding another column works w/o issues.
However, the empty grid pane is not visible in layout view but in hierarchy.

@abhinayagarwal 
This one can be closed.
