### ISSUE TITLE
Excessive RAM memory consumption

### ISSUE THREAD

**Issue by gluon-bot** [gluonhq/scenebuilder#96]
Originally reported by: **Rogério Queiroz (Bitbucket: [rogeriomq](https://bitbucket.org/rogeriomq), GitHub: [rogeriomq](https://github.com/rogeriomq))**

----------------------------------------

Scene Builder version 8.2.0 has growth of RAM until locking the notebook. I have 8G of RAM and use Fedora 24 (currently Fedora25) 64bit.
As I add components, edit properties, etc, the memory grows to the point of occupying all memory and freezing the computer.

----------------------------------------
- Bitbucket: https://bitbucket.org/gluon-oss/scenebuilder/issue/96

**Comment by abhinayagarwal** [comment]
This has been fixed in the underlying platform.
